/** Shared forbidden analytics property fragments for OVE-200 reconcile gates. */
export const FORBIDDEN_ANALYTICS_PROPERTY_FRAGMENTS = [
  "address",
  "body",
  "content",
  "coordinate",
  "derivative_key",
  "email",
  "exif",
  "file_name",
  "filename",
  "ip",
  "lat",
  "latitude",
  "lng",
  "lon",
  "longitude",
  "media_metadata",
  "metadata",
  "quarantine",
  "query",
  "raw",
  "referrer",
  "text",
  "title",
  "url",
  "user_agent",
  "user_id",
  "session_recording",
] as const;
