import type { InterfaceLocale } from "@/lib/interface-localization";

export const COARSE_REGIONS = [
  { code: "UA-05", countryCode: "UA", label: "Ukraine - Vinnytsia Oblast" },
  { code: "UA-07", countryCode: "UA", label: "Ukraine - Volyn Oblast" },
  { code: "UA-09", countryCode: "UA", label: "Ukraine - Luhansk Oblast" },
  {
    code: "UA-12",
    countryCode: "UA",
    label: "Ukraine - Dnipropetrovsk Oblast",
  },
  { code: "UA-14", countryCode: "UA", label: "Ukraine - Donetsk Oblast" },
  { code: "UA-18", countryCode: "UA", label: "Ukraine - Zhytomyr Oblast" },
  {
    code: "UA-21",
    countryCode: "UA",
    label: "Ukraine - Zakarpattia Oblast",
  },
  { code: "UA-23", countryCode: "UA", label: "Ukraine - Zaporizhzhia Oblast" },
  {
    code: "UA-26",
    countryCode: "UA",
    label: "Ukraine - Ivano-Frankivsk Oblast",
  },
  { code: "UA-30", countryCode: "UA", label: "Ukraine - Kyiv City" },
  { code: "UA-32", countryCode: "UA", label: "Ukraine - Kyiv Oblast" },
  { code: "UA-35", countryCode: "UA", label: "Ukraine - Kirovohrad Oblast" },
  { code: "UA-40", countryCode: "UA", label: "Ukraine - Sevastopol" },
  { code: "UA-43", countryCode: "UA", label: "Ukraine - Crimea" },
  { code: "UA-46", countryCode: "UA", label: "Ukraine - Lviv Oblast" },
  { code: "UA-48", countryCode: "UA", label: "Ukraine - Mykolaiv Oblast" },
  { code: "UA-51", countryCode: "UA", label: "Ukraine - Odesa Oblast" },
  { code: "UA-53", countryCode: "UA", label: "Ukraine - Poltava Oblast" },
  { code: "UA-56", countryCode: "UA", label: "Ukraine - Rivne Oblast" },
  { code: "UA-59", countryCode: "UA", label: "Ukraine - Sumy Oblast" },
  { code: "UA-61", countryCode: "UA", label: "Ukraine - Ternopil Oblast" },
  { code: "UA-63", countryCode: "UA", label: "Ukraine - Kharkiv Oblast" },
  { code: "UA-65", countryCode: "UA", label: "Ukraine - Kherson Oblast" },
  {
    code: "UA-68",
    countryCode: "UA",
    label: "Ukraine - Khmelnytskyi Oblast",
  },
  { code: "UA-71", countryCode: "UA", label: "Ukraine - Cherkasy Oblast" },
  { code: "UA-74", countryCode: "UA", label: "Ukraine - Chernihiv Oblast" },
  { code: "UA-77", countryCode: "UA", label: "Ukraine - Chernivtsi Oblast" },
  {
    code: "BG-01",
    countryCode: "BG",
    label: "Bulgaria - Blagoevgrad Province",
  },
  { code: "BG-02", countryCode: "BG", label: "Bulgaria - Burgas Province" },
  { code: "BG-03", countryCode: "BG", label: "Bulgaria - Varna Province" },
  {
    code: "BG-04",
    countryCode: "BG",
    label: "Bulgaria - Veliko Tarnovo Province",
  },
  { code: "BG-05", countryCode: "BG", label: "Bulgaria - Vidin Province" },
  { code: "BG-06", countryCode: "BG", label: "Bulgaria - Vratsa Province" },
  { code: "BG-07", countryCode: "BG", label: "Bulgaria - Gabrovo Province" },
  { code: "BG-08", countryCode: "BG", label: "Bulgaria - Dobrich Province" },
  { code: "BG-09", countryCode: "BG", label: "Bulgaria - Kardzhali Province" },
  {
    code: "BG-10",
    countryCode: "BG",
    label: "Bulgaria - Kyustendil Province",
  },
  { code: "BG-11", countryCode: "BG", label: "Bulgaria - Lovech Province" },
  { code: "BG-12", countryCode: "BG", label: "Bulgaria - Montana Province" },
  {
    code: "BG-13",
    countryCode: "BG",
    label: "Bulgaria - Pazardzhik Province",
  },
  { code: "BG-14", countryCode: "BG", label: "Bulgaria - Pernik Province" },
  { code: "BG-15", countryCode: "BG", label: "Bulgaria - Pleven Province" },
  { code: "BG-16", countryCode: "BG", label: "Bulgaria - Plovdiv Province" },
  { code: "BG-17", countryCode: "BG", label: "Bulgaria - Razgrad Province" },
  { code: "BG-18", countryCode: "BG", label: "Bulgaria - Ruse Province" },
  { code: "BG-19", countryCode: "BG", label: "Bulgaria - Silistra Province" },
  { code: "BG-20", countryCode: "BG", label: "Bulgaria - Sliven Province" },
  { code: "BG-21", countryCode: "BG", label: "Bulgaria - Smolyan Province" },
  {
    code: "BG-22",
    countryCode: "BG",
    label: "Bulgaria - Sofia City Province",
  },
  { code: "BG-23", countryCode: "BG", label: "Bulgaria - Sofia Province" },
  {
    code: "BG-24",
    countryCode: "BG",
    label: "Bulgaria - Stara Zagora Province",
  },
  {
    code: "BG-25",
    countryCode: "BG",
    label: "Bulgaria - Targovishte Province",
  },
  { code: "BG-26", countryCode: "BG", label: "Bulgaria - Haskovo Province" },
  { code: "BG-27", countryCode: "BG", label: "Bulgaria - Shumen Province" },
  { code: "BG-28", countryCode: "BG", label: "Bulgaria - Yambol Province" },
] as const;

export type CoarseRegionCode = (typeof COARSE_REGIONS)[number]["code"];

const LOCALIZED_COARSE_REGION_LABELS = {
  uk: {
    "UA-05": "Україна — Вінницька область",
    "UA-07": "Україна — Волинська область",
    "UA-09": "Україна — Луганська область",
    "UA-12": "Україна — Дніпропетровська область",
    "UA-14": "Україна — Донецька область",
    "UA-18": "Україна — Житомирська область",
    "UA-21": "Україна — Закарпатська область",
    "UA-23": "Україна — Запорізька область",
    "UA-26": "Україна — Івано-Франківська область",
    "UA-30": "Україна — місто Київ",
    "UA-32": "Україна — Київська область",
    "UA-35": "Україна — Кіровоградська область",
    "UA-40": "Україна — Севастополь",
    "UA-43": "Україна — Автономна Республіка Крим",
    "UA-46": "Україна — Львівська область",
    "UA-48": "Україна — Миколаївська область",
    "UA-51": "Україна — Одеська область",
    "UA-53": "Україна — Полтавська область",
    "UA-56": "Україна — Рівненська область",
    "UA-59": "Україна — Сумська область",
    "UA-61": "Україна — Тернопільська область",
    "UA-63": "Україна — Харківська область",
    "UA-65": "Україна — Херсонська область",
    "UA-68": "Україна — Хмельницька область",
    "UA-71": "Україна — Черкаська область",
    "UA-74": "Україна — Чернігівська область",
    "UA-77": "Україна — Чернівецька область",
    "BG-01": "Болгарія — Благоєвградська область",
    "BG-02": "Болгарія — Бургаська область",
    "BG-03": "Болгарія — Варненська область",
    "BG-04": "Болгарія — Великотирновська область",
    "BG-05": "Болгарія — Видинська область",
    "BG-06": "Болгарія — Врацька область",
    "BG-07": "Болгарія — Габровська область",
    "BG-08": "Болгарія — Добричська область",
    "BG-09": "Болгарія — Кирджалійська область",
    "BG-10": "Болгарія — Кюстендильська область",
    "BG-11": "Болгарія — Ловецька область",
    "BG-12": "Болгарія — Монтанська область",
    "BG-13": "Болгарія — Пазарджицька область",
    "BG-14": "Болгарія — Перницька область",
    "BG-15": "Болгарія — Плевенська область",
    "BG-16": "Болгарія — Пловдивська область",
    "BG-17": "Болгарія — Разградська область",
    "BG-18": "Болгарія — Русенська область",
    "BG-19": "Болгарія — Сілістренська область",
    "BG-20": "Болгарія — Сливенська область",
    "BG-21": "Болгарія — Смолянська область",
    "BG-22": "Болгарія — місто Софія",
    "BG-23": "Болгарія — Софійська область",
    "BG-24": "Болгарія — Старозагорська область",
    "BG-25": "Болгарія — Тирговиштська область",
    "BG-26": "Болгарія — Хасковська область",
    "BG-27": "Болгарія — Шуменська область",
    "BG-28": "Болгарія — Ямбольська область",
  },
  bg: {
    "UA-05": "Украйна — Виницка област",
    "UA-07": "Украйна — Волинска област",
    "UA-09": "Украйна — Луганска област",
    "UA-12": "Украйна — Днепропетровска област",
    "UA-14": "Украйна — Донецка област",
    "UA-18": "Украйна — Житомирска област",
    "UA-21": "Украйна — Закарпатска област",
    "UA-23": "Украйна — Запорожка област",
    "UA-26": "Украйна — Ивано-Франковска област",
    "UA-30": "Украйна — град Киев",
    "UA-32": "Украйна — Киевска област",
    "UA-35": "Украйна — Кировоградска област",
    "UA-40": "Украйна — Севастопол",
    "UA-43": "Украйна — Автономна република Крим",
    "UA-46": "Украйна — Лвовска област",
    "UA-48": "Украйна — Николаевска област",
    "UA-51": "Украйна — Одеска област",
    "UA-53": "Украйна — Полтавска област",
    "UA-56": "Украйна — Ровненска област",
    "UA-59": "Украйна — Сумска област",
    "UA-61": "Украйна — Тернополска област",
    "UA-63": "Украйна — Харковска област",
    "UA-65": "Украйна — Херсонска област",
    "UA-68": "Украйна — Хмелницка област",
    "UA-71": "Украйна — Черкаска област",
    "UA-74": "Украйна — Черниговска област",
    "UA-77": "Украйна — Черновицка област",
    "BG-01": "България — област Благоевград",
    "BG-02": "България — област Бургас",
    "BG-03": "България — област Варна",
    "BG-04": "България — област Велико Търново",
    "BG-05": "България — област Видин",
    "BG-06": "България — област Враца",
    "BG-07": "България — област Габрово",
    "BG-08": "България — област Добрич",
    "BG-09": "България — област Кърджали",
    "BG-10": "България — област Кюстендил",
    "BG-11": "България — област Ловеч",
    "BG-12": "България — област Монтана",
    "BG-13": "България — област Пазарджик",
    "BG-14": "България — област Перник",
    "BG-15": "България — област Плевен",
    "BG-16": "България — област Пловдив",
    "BG-17": "България — област Разград",
    "BG-18": "България — област Русе",
    "BG-19": "България — област Силистра",
    "BG-20": "България — област Сливен",
    "BG-21": "България — област Смолян",
    "BG-22": "България — София-град",
    "BG-23": "България — Софийска област",
    "BG-24": "България — област Стара Загора",
    "BG-25": "България — област Търговище",
    "BG-26": "България — област Хасково",
    "BG-27": "България — област Шумен",
    "BG-28": "България — област Ямбол",
  },
  ru: {
    "UA-05": "Украина — Винницкая область",
    "UA-07": "Украина — Волынская область",
    "UA-09": "Украина — Луганская область",
    "UA-12": "Украина — Днепропетровская область",
    "UA-14": "Украина — Донецкая область",
    "UA-18": "Украина — Житомирская область",
    "UA-21": "Украина — Закарпатская область",
    "UA-23": "Украина — Запорожская область",
    "UA-26": "Украина — Ивано-Франковская область",
    "UA-30": "Украина — город Киев",
    "UA-32": "Украина — Киевская область",
    "UA-35": "Украина — Кировоградская область",
    "UA-40": "Украина — Севастополь",
    "UA-43": "Украина — Республика Крым",
    "UA-46": "Украина — Львовская область",
    "UA-48": "Украина — Николаевская область",
    "UA-51": "Украина — Одесская область",
    "UA-53": "Украина — Полтавская область",
    "UA-56": "Украина — Ровненская область",
    "UA-59": "Украина — Сумская область",
    "UA-61": "Украина — Тернопольская область",
    "UA-63": "Украина — Харьковская область",
    "UA-65": "Украина — Херсонская область",
    "UA-68": "Украина — Хмельницкая область",
    "UA-71": "Украина — Черкасская область",
    "UA-74": "Украина — Черниговская область",
    "UA-77": "Украина — Черновицкая область",
    "BG-01": "Болгария — Благоевградская область",
    "BG-02": "Болгария — Бургасская область",
    "BG-03": "Болгария — Варненская область",
    "BG-04": "Болгария — Великотырновская область",
    "BG-05": "Болгария — Видинская область",
    "BG-06": "Болгария — Врачанская область",
    "BG-07": "Болгария — Габровская область",
    "BG-08": "Болгария — Добричская область",
    "BG-09": "Болгария — Кырджалийская область",
    "BG-10": "Болгария — Кюстендилская область",
    "BG-11": "Болгария — Ловечская область",
    "BG-12": "Болгария — Монтанская область",
    "BG-13": "Болгария — Пазарджикская область",
    "BG-14": "Болгария — Перникская область",
    "BG-15": "Болгария — Плевенская область",
    "BG-16": "Болгария — Пловдивская область",
    "BG-17": "Болгария — Разградская область",
    "BG-18": "Болгария — Русенская область",
    "BG-19": "Болгария — Силистренская область",
    "BG-20": "Болгария — Сливенская область",
    "BG-21": "Болгария — Смолянская область",
    "BG-22": "Болгария — город София",
    "BG-23": "Болгария — Софийская область",
    "BG-24": "Болгария — Старозагорская область",
    "BG-25": "Болгария — Тырговиштская область",
    "BG-26": "Болгария — Хасковская область",
    "BG-27": "Болгария — Шуменская область",
    "BG-28": "Болгария — Ямболская область",
  },
} as const satisfies Record<InterfaceLocale, Record<CoarseRegionCode, string>>;

export const COARSE_REGION_OPTIONS = COARSE_REGIONS.map(({ code, label }) => ({
  value: code,
  label,
}));

const COARSE_REGION_LABELS = new Map<string, string>(
  COARSE_REGIONS.map((region) => [region.code, region.label]),
);

export function normalizeCoarseRegionCode(
  value: string | null | undefined,
): CoarseRegionCode | null {
  const normalized = value?.trim().toUpperCase() ?? "";
  return COARSE_REGION_LABELS.has(normalized)
    ? (normalized as CoarseRegionCode)
    : null;
}

export function isCoarseRegionCode(
  value: string | null | undefined,
): value is CoarseRegionCode {
  return normalizeCoarseRegionCode(value) !== null;
}

export function getCoarseRegionLabel(
  value: string | null | undefined,
): string | null {
  const normalized = normalizeCoarseRegionCode(value);
  return normalized ? (COARSE_REGION_LABELS.get(normalized) ?? null) : null;
}

export function getLocalizedCoarseRegionLabel(
  locale: InterfaceLocale,
  value: string | null | undefined,
) {
  const normalized = normalizeCoarseRegionCode(value);
  return normalized ? LOCALIZED_COARSE_REGION_LABELS[locale][normalized] : null;
}

export function getLocalizedCoarseRegionOptions(locale: InterfaceLocale) {
  return COARSE_REGIONS.map(({ code }) => ({
    value: code,
    label: LOCALIZED_COARSE_REGION_LABELS[locale][code],
  }));
}
