declare namespace Cloudflare {
  interface Env {
    EPHEMERAL_MEDIA_CAPABILITY_SECRETS: string;
    EPHEMERAL_MEDIA_CAPABILITY_CURRENT_VERSION: string;
    EPHEMERAL_MEDIA_RECEIPT_SECRETS: string;
    EPHEMERAL_MEDIA_RECEIPT_CURRENT_VERSION: string;
    EPHEMERAL_MEDIA_COMMIT_STATUS_SECRET: string;
  }
}
