/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Health {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  message: string;
}

export interface JobQueue {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string | null;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  payload: Json;
  queue_name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface JournalEntries {
  body: string;
  client_mutation_id: string;
  created_at: Generated<Timestamp>;
  entry_date: Generated<Timestamp>;
  entry_scope: Generated<string>;
  first_publication_disclosed_at: Timestamp | null;
  first_publication_disclosure_version: string | null;
  id: Generated<string>;
  owner_user_id: string;
  plant_object_id: string;
  public_noindex: Generated<boolean>;
  public_slug: string | null;
  published_at: Timestamp | null;
  space_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface MediaAssets {
  created_at: Generated<Timestamp>;
  derivative_key: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  original_deleted_at: Timestamp | null;
  owner_user_id: string;
  quarantine_key: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PlantObjects {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  location_visibility: Generated<string>;
  owner_user_id: string;
  space_id: string;
  updated_at: Generated<Timestamp>;
  variety_state: Generated<string>;
  variety_text: string | null;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Spaces {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  location_visibility: Generated<string>;
  owner_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  health: Health;
  job_queue: JobQueue;
  journal_entries: JournalEntries;
  media_assets: MediaAssets;
  plant_objects: PlantObjects;
  session: Session;
  spaces: Spaces;
  user: User;
  verification: Verification;
}
