/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AdminRoleAuditLog {
  action: string;
  actor_session_id_hash: string | null;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  new_role: string | null;
  previous_role: string | null;
  reason: Generated<string>;
  target_user_id: string | null;
}

export interface AdminUserRoles {
  grant_reason: Generated<string>;
  granted_at: Generated<Timestamp>;
  granted_by_user_id: string | null;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AnalyticsEvents {
  created_at: Generated<Timestamp>;
  event_name: string;
  id: Generated<string>;
  journal_entry_id: string | null;
  owner_user_id: string;
  plant_object_id: string | null;
  properties: Generated<Json>;
  related_event_id: string | null;
  session_id: string | null;
  space_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CatalogAliasProjections {
  alias_kind: string;
  attribution_required: Generated<boolean>;
  catalog_item_id: string;
  catalog_item_name_id: string | null;
  confidence: Numeric;
  created_at: Generated<Timestamp>;
  decision_reason_code: string | null;
  decision_result: string | null;
  display_name: string;
  generated_at: Generated<Timestamp>;
  generated_from_catalog_item_name_id: string | null;
  generator_version: string | null;
  id: Generated<string>;
  license: string;
  locale: Generated<string>;
  normalized_name: string;
  projection_notes: string | null;
  reason_codes: Generated<string[]>;
  reviewed_at: Timestamp | null;
  reviewed_by_user_id: string | null;
  script: Generated<string>;
  source_method: string;
  source_name_fingerprint: string | null;
  source_record_id: string | null;
  source_record_key: string | null;
  source_slug: string;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface CatalogFuzzyDuplicateSuggestions {
  generated_at: Generated<Timestamp>;
  id: Generated<string>;
  left_catalog_item_id: string;
  left_updated_at_snapshot: Timestamp;
  locale_relation: string;
  matcher_version: string;
  pair_key: string;
  reason_codes: string[];
  recommended_action: string;
  right_catalog_item_id: string;
  right_updated_at_snapshot: Timestamp;
  score: number;
  score_bucket: string;
  updated_at: Generated<Timestamp>;
}

export interface CatalogItemNames {
  catalog_item_id: string;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  locale: Generated<string>;
  normalized_name: string;
}

export interface CatalogItems {
  canonical_name: string;
  catalog_kind: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  id: Generated<string>;
  locale: Generated<string>;
  merged_into_catalog_item_id: string | null;
  normalized_name: string | null;
  public_slug: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by_user_id: string | null;
  source: Generated<string>;
  source_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CatalogMatchSuggestions {
  affected_object_count: Generated<number>;
  candidate_key: string;
  catalog_kind: string;
  confidence_bucket: string;
  created_at: Generated<Timestamp>;
  decision_affected_object_count: number | null;
  decision_reason_code: string | null;
  decision_result: string | null;
  generated_at: Generated<Timestamp>;
  id: Generated<string>;
  match_type: string;
  matched_name: string | null;
  matcher_version: string;
  normalized_input: string;
  reason_codes: Generated<string[]>;
  reviewed_at: Timestamp | null;
  reviewed_by_user_id: string | null;
  safe_evidence: Json;
  score: number;
  source_catalog_item_id: string;
  source_locale: Generated<string>;
  source_matching_fingerprint: string | null;
  source_script: string;
  source_updated_at_snapshot: Timestamp | null;
  status: Generated<string>;
  suggestion_kind: Generated<string>;
  target_canonical_name: string | null;
  target_catalog_item_id: string | null;
  target_catalog_item_name_id: string | null;
  target_locale: string | null;
  target_matching_fingerprint: string | null;
  target_script: string | null;
  target_updated_at_snapshot: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface CatalogSourceLinks {
  catalog_item_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  projection_kind: Generated<string>;
  source_record_id: string;
  source_record_key: string;
  source_slug: string;
}

export interface CatalogSourceRecords {
  allowed_projection: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  projection_status: Generated<string>;
  raw_payload: Json;
  raw_payload_sha256: string;
  source_only_fields: Generated<Json>;
  source_record_id: string;
  source_snapshot_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CatalogSourceRefreshEvents {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  payload_sha256: string;
  previous_snapshot_id: string;
  refresh_label: string;
  refreshed_snapshot_id: string;
  source_slug: string;
  summary: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface CatalogSourceRefreshRecords {
  catalog_item_id: string | null;
  created_at: Generated<Timestamp>;
  diff_status: string;
  id: Generated<string>;
  previous_source_record_id: string | null;
  projection_action: string;
  refresh_event_id: string;
  refreshed_source_record_id: string | null;
  reindex_required: Generated<boolean>;
  review_reason: string | null;
  safe_diff: Generated<Json>;
  source_record_key: string;
  updated_at: Generated<Timestamp>;
}

export interface CatalogSourceSnapshots {
  allowed_usage: Generated<Json>;
  attribution_required: Generated<boolean>;
  attribution_text: string | null;
  created_at: Generated<Timestamp>;
  fetched_at: Timestamp;
  id: Generated<string>;
  license: string;
  license_url: string | null;
  parser_version: string;
  payload_sha256: string;
  source_category: string;
  source_name: string;
  source_slug: string;
  source_url: string;
  source_version: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  verified_at: Timestamp;
}

export interface Communities {
  content_key: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  journal_topic_id: string;
  lifecycle_state: Generated<string>;
  minimum_ready_contributions: Generated<number>;
  participation_state: Generated<string>;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface CommunityContributionReports {
  contribution_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  report_reason: string;
  report_state: Generated<string>;
  reporter_user_id: string;
  resolved_at: Timestamp | null;
  resolved_by_user_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CommunityContributions {
  added_at: Generated<Timestamp>;
  community_id: string;
  contribution_state: Generated<string>;
  contributor_user_id: string;
  discussion_state: Generated<string>;
  id: Generated<string>;
  journal_entry_id: string;
  removal_reason: string | null;
  removed_at: Timestamp | null;
  removed_by_user_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface CommunityMemberships {
  banned_at: Timestamp | null;
  community_id: string;
  id: Generated<string>;
  joined_at: Generated<Timestamp>;
  left_at: Timestamp | null;
  membership_state: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface CommunityModerationAuditLog {
  action: string;
  actor_user_id: string;
  community_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  new_state: string;
  previous_state: string;
  reason: string;
  target_id: string;
  target_kind: string;
}

export interface CommunityModerators {
  assignment_state: Generated<string>;
  community_id: string;
  granted_at: Generated<Timestamp>;
  granted_by_user_id: string | null;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface CommunityRules {
  community_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  rule_key: string;
  rule_state: Generated<string>;
  sort_order: number;
  updated_at: Generated<Timestamp>;
}

export interface EngagementBookmarks {
  bookmark_state: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  owner_user_id: string;
  target_kind: string;
  target_ref: string;
  updated_at: Generated<Timestamp>;
}

export interface EngagementCommentReports {
  comment_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  report_reason: string;
  report_state: Generated<string>;
  reporter_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface EngagementComments {
  author_user_id: string;
  body: string;
  client_mutation_id: string;
  comment_state: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  parent_comment_id: string | null;
  target_kind: string;
  target_ref: string;
  updated_at: Generated<Timestamp>;
}

export interface EngagementFollows {
  created_at: Generated<Timestamp>;
  follow_state: Generated<string>;
  follower_user_id: string;
  id: Generated<string>;
  target_kind: string;
  target_ref: string;
  updated_at: Generated<Timestamp>;
}

export interface EngagementLikes {
  anonymous_device_hash: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  like_state: Generated<string>;
  target_kind: string;
  target_ref: string;
  toggle_count: Generated<number>;
  toggle_window_started_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface ErasureRequests {
  created_at: Generated<Timestamp>;
  dry_run_reviewed_at: Timestamp | null;
  dry_run_reviewed_by_user_id: string | null;
  handled_at: Timestamp | null;
  handled_by_user_id: string | null;
  handled_status: string | null;
  id: Generated<string>;
  intake_disclosure_version: Generated<string>;
  request_scope: Generated<string>;
  requester_user_id: string;
  status: Generated<string>;
  submitted_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Health {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  message: string;
}

export interface JobQueue {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string | null;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  payload: Json;
  queue_name: string;
  rerun_requested: Generated<boolean>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface JournalEntries {
  archived_at: Timestamp | null;
  body: string;
  client_mutation_id: string;
  content_document: Json | null;
  content_schema_version: number | null;
  created_at: Generated<Timestamp>;
  entry_date: Generated<Timestamp>;
  entry_scope: Generated<string>;
  first_publication_disclosed_at: Timestamp | null;
  first_publication_disclosure_version: string | null;
  id: Generated<string>;
  journal_revision: Generated<Numeric>;
  cover_media_asset_id: string | null;
  lifecycle_state: Generated<string>;
  owner_user_id: string;
  plant_object_id: string | null;
  public_gone_at: Timestamp | null;
  public_noindex: Generated<boolean>;
  public_slug: string | null;
  published_at: Timestamp | null;
  space_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface JournalEntryMutationReceipts {
  base_revision: Numeric;
  client_mutation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  journal_entry_id: string;
  mutation_kind: string;
  owner_user_id: string;
  result_revision: Numeric;
}

export interface JournalEntryCatalogMentions {
  catalog_item_id: string;
  created_at: Generated<Timestamp>;
  journal_entry_id: string;
  owner_user_id: string;
  space_id: string;
}

export interface JournalEntryObjectMentions {
  created_at: Generated<Timestamp>;
  journal_entry_id: string;
  owner_user_id: string;
  plant_object_id: string;
  space_id: string;
}

export interface JournalEntryTopicSignals {
  created_at: Generated<Timestamp>;
  journal_entry_id: string;
  public_membership_state: Generated<string>;
  review_state: Generated<string>;
  signal_source: string;
  topic_id: string;
  updated_at: Generated<Timestamp>;
}

export interface JournalTopics {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label: string;
  slug: string;
  trust_state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LineageNodeFollows {
  created_at: Generated<Timestamp>;
  follow_state: Generated<string>;
  follower_user_id: string;
  id: Generated<string>;
  lineage_edge_id: string;
  target_owner_user_id: string;
  target_plant_object_id: string;
  updated_at: Generated<Timestamp>;
}

export interface LineagePendingSourceIdentities {
  claimed_at: Timestamp | null;
  claimed_by_user_id: string | null;
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  display_label: string;
  id: Generated<string>;
  invite_state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LineageProvenanceEdgeAuditEvents {
  action: string;
  actor_user_id: string | null;
  created_at: Generated<Timestamp>;
  edge_id: string;
  id: Generated<string>;
  new_consent_state: string;
  previous_consent_state: string;
  target_user_id: string | null;
  visibility_policy: string;
}

export interface LineageProvenanceEdges {
  client_mutation_id: string;
  consent_state: Generated<string>;
  created_at: Generated<Timestamp>;
  edge_type: Generated<string>;
  erasure_state: Generated<string>;
  id: Generated<string>;
  owner_user_id: string;
  source_kind: string;
  source_owner_user_id: string | null;
  source_pending_identity_id: string | null;
  source_plant_object_id: string | null;
  source_reference_kind: string | null;
  source_reference_label: string | null;
  subject_plant_object_id: string;
  updated_at: Generated<Timestamp>;
  visibility_policy: Generated<string>;
}

export interface LineageQuestions {
  asker_user_id: string;
  client_mutation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  lineage_edge_id: string;
  question_state: Generated<string>;
  question_text: string;
  recipient_user_id: string;
  subject_plant_object_id: string;
  target_plant_object_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MatchingWorkerHeartbeats {
  image_digest: string;
  queue_name: string;
  release_commit_sha: string;
  schema_compatibility_class: string;
  seen_at: Generated<Timestamp>;
  supported_handlers: string[];
  updated_at: Generated<Timestamp>;
}

export interface MediaAssets {
  alt_text: string | null;
  caption: string | null;
  created_at: Generated<Timestamp>;
  derivative_key: string | null;
  document_position: number | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  original_deleted_at: Timestamp | null;
  owner_user_id: string;
  quarantine_key: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  usage_role: Generated<string>;
}

export interface NotificationPreferences {
  claims_enabled: Generated<boolean>;
  comments_enabled: Generated<boolean>;
  created_at: Generated<Timestamp>;
  follows_enabled: Generated<boolean>;
  mentions_enabled: Generated<boolean>;
  owner_user_id: string;
  replies_enabled: Generated<boolean>;
  system_enabled: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface NotificationReceipts {
  created_at: Generated<Timestamp>;
  event_key: string;
  id: Generated<string>;
  owner_user_id: string;
  read_at: Timestamp | null;
  receipt_state: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PilotInterviewLearnings {
  activation_result: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  main_objection: string;
  next_action: string;
  observed_value: string;
  pilot_cohort: string | null;
  recorded_at: Generated<Timestamp>;
  recorded_by_user_id: string;
  redacted_note: string | null;
  return_reason: string;
  segment: string;
  subject_user_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PilotInviteGrants {
  cohort: Generated<string>;
  created_at: Generated<Timestamp>;
  granted_at: Generated<Timestamp>;
  segment: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PlantObjects {
  catalog_item_id: string | null;
  coarse_region_code: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  location_visibility: Generated<string>;
  object_kind: Generated<string>;
  owner_user_id: string;
  space_id: string;
  updated_at: Generated<Timestamp>;
  variety_state: Generated<string>;
  variety_text: string | null;
}

export interface ProfileBlocks {
  block_state: Generated<string>;
  blocked_user_id: string;
  blocker_user_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ProfileFollows {
  created_at: Generated<Timestamp>;
  follow_state: Generated<string>;
  follower_user_id: string;
  id: Generated<string>;
  target_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ProfileReports {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  report_reason: string;
  report_state: Generated<string>;
  reporter_user_id: string;
  target_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Spaces {
  coarse_region_code: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  location_visibility: Generated<string>;
  owner_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserHandleRegistry {
  claim_source: string;
  claimed_at: Generated<Timestamp>;
  lifecycle_state: Generated<string>;
  next_rename_at: Generated<Timestamp>;
  normalized_handle: string;
  policy_version: Generated<string>;
  retired_at: Timestamp | null;
  user_id: string;
}

export interface UserPublicProfiles {
  avatar_media_asset_id: string | null;
  avatar_url: string | null;
  bio: string | null;
  coarse_region_code: string | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  display_name_policy_version: string | null;
  handle: string;
  handle_changed_at: Timestamp | null;
  handle_registry_state: Generated<string>;
  identity_policy_version: Generated<string>;
  languages: Generated<string[]>;
  location_visibility: Generated<string>;
  normalized_handle: string;
  profile_lifecycle_state: Generated<string>;
  profile_visibility: Generated<string>;
  relationship_visibility: Generated<string>;
  removed_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface VarietySeedProofs {
  author_user_id: string;
  body: string;
  catalog_item_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  published_at: Timestamp | null;
  source_label: string | null;
  status: Generated<string>;
  summary: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface WishlistItems {
  catalog_item_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  owner_user_id: string;
  source_surface: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  account: Account;
  admin_role_audit_log: AdminRoleAuditLog;
  admin_user_roles: AdminUserRoles;
  analytics_events: AnalyticsEvents;
  catalog_alias_projections: CatalogAliasProjections;
  catalog_fuzzy_duplicate_suggestions: CatalogFuzzyDuplicateSuggestions;
  catalog_item_names: CatalogItemNames;
  catalog_items: CatalogItems;
  catalog_match_suggestions: CatalogMatchSuggestions;
  catalog_source_links: CatalogSourceLinks;
  catalog_source_records: CatalogSourceRecords;
  catalog_source_refresh_events: CatalogSourceRefreshEvents;
  catalog_source_refresh_records: CatalogSourceRefreshRecords;
  catalog_source_snapshots: CatalogSourceSnapshots;
  communities: Communities;
  community_contribution_reports: CommunityContributionReports;
  community_contributions: CommunityContributions;
  community_memberships: CommunityMemberships;
  community_moderation_audit_log: CommunityModerationAuditLog;
  community_moderators: CommunityModerators;
  community_rules: CommunityRules;
  engagement_bookmarks: EngagementBookmarks;
  engagement_comment_reports: EngagementCommentReports;
  engagement_comments: EngagementComments;
  engagement_follows: EngagementFollows;
  engagement_likes: EngagementLikes;
  erasure_requests: ErasureRequests;
  health: Health;
  job_queue: JobQueue;
  journal_entries: JournalEntries;
  journal_entry_catalog_mentions: JournalEntryCatalogMentions;
  journal_entry_mutation_receipts: JournalEntryMutationReceipts;
  journal_entry_object_mentions: JournalEntryObjectMentions;
  journal_entry_topic_signals: JournalEntryTopicSignals;
  journal_topics: JournalTopics;
  lineage_node_follows: LineageNodeFollows;
  lineage_pending_source_identities: LineagePendingSourceIdentities;
  lineage_provenance_edge_audit_events: LineageProvenanceEdgeAuditEvents;
  lineage_provenance_edges: LineageProvenanceEdges;
  lineage_questions: LineageQuestions;
  matching_worker_heartbeats: MatchingWorkerHeartbeats;
  media_assets: MediaAssets;
  notification_preferences: NotificationPreferences;
  notification_receipts: NotificationReceipts;
  pilot_interview_learnings: PilotInterviewLearnings;
  pilot_invite_grants: PilotInviteGrants;
  plant_objects: PlantObjects;
  profile_blocks: ProfileBlocks;
  profile_follows: ProfileFollows;
  profile_reports: ProfileReports;
  session: Session;
  spaces: Spaces;
  user: User;
  user_handle_registry: UserHandleRegistry;
  user_public_profiles: UserPublicProfiles;
  variety_seed_proofs: VarietySeedProofs;
  verification: Verification;
  wishlist_items: WishlistItems;
}
