import type { InterfaceLocale } from "@/lib/interface-localization";
import type { WidenCopy } from "@/lib/operator-copy";

const UK_COPY = {
  page: {
    metadataTitle: "Курація каталогу | OverGarden",
    metadataDescription:
      "Захищений операторський простір перевірки ідентичностей, джерел і доказів каталогу OverGarden.",
    gardenJournal: "Журнал саду",
    backToJournal: "Назад до журналу",
    title: "Курація каталогу",
    accessDenied: "Доступ заборонено.",
    pending: "Очікують",
    seedProofs: "Блоки доказів",
    aliasReview: "Перевірка назв",
    sourceCandidates: "Кандидати з джерел",
    sourceRows: "Рядки джерел",
    gate: "Режим доступу",
    sealedOwner: "захищений власник",
    role: "Роль",
  },
  common: {
    rows: "Рядки",
    all: "Усі",
    version: "Версія",
    unknown: "Невідомо",
    source: "Джерело",
    license: "Ліцензія",
    parser: "Парсер",
    verified: "Перевірено",
    fetched: "Отримано",
    attribution: "Атрибуція",
    attributionRequired: "потрібна атрибуція",
    publicPage: "Публічна сторінка",
    species: "Вид",
    candidateKind: "Тип кандидата",
    reviewNote: "Примітка перевірки",
    aliases: "назв",
    primary: "основна",
    typeahead: "пошук під час введення",
    typeaheadNames: "Назви для пошуку",
    confidence: "Впевненість",
    status: "Статус",
    updated: "Оновлено",
    selected: "Вибрано",
    searching: "Пошук...",
    suggestionsUnavailable: "Підказки недоступні.",
    applying: "Застосування...",
    queueing: "Додавання в чергу...",
    refreshQueued: "Оновлення додано в чергу",
    rejectionReason: "Причина відхилення",
    statuses: {
      quarantined: "У карантині",
      held: "Утримано",
      review_needed: "Потрібна перевірка",
      blocked: "Заблоковано",
      rejected: "Відхилено",
      promoted: "Опубліковано",
      provisional: "Попередній",
      seeded: "Початковий каталог",
      confirmed: "Підтверджено",
      draft: "Чернетка",
      published: "Опубліковано",
      accepted: "Прийнято",
      generated: "Згенеровано",
      current: "Актуально",
      stale: "Застаріло",
      passed: "Пройдено",
    },
    catalogKinds: {
      plant_variety: "Сорт рослини",
      species: "Вид",
      breed: "Порода",
      identity: "Ідентичність каталогу",
    },
  },
  alias: {
    title: "Підказки назв і локалей",
    description:
      "Створюйте детерміновані варіанти написання й транслітерації з підтвердженої ідентичності каталогу. Згенерований рядок потрапляє до пошуку лише після явного схвалення.",
    searchLabel: "Пошук ідентичності каталогу",
    searchPlaceholder: "Пошук канонічної або прийнятої назви",
    search: "Шукати",
    reviewQueue: "Черга перевірки",
    noGenerated: "Згенерованих підказок назв ще немає.",
    searchPrompt: "Знайдіть ідентичність каталогу, щоб створити варіанти.",
    noMatches: "Глобальних ідентичностей каталогу за цим запитом не знайдено.",
    acceptedNames: "Прийнятих назв",
    generatedFrom: "створено з",
    collision:
      "Схвалення заблоковано, бо нормалізована назва веде до іншої ідентичності каталогу. Усуньте конфлікт і створіть варіанти повторно.",
    decision: "Рішення",
    searchable: "Доступна в пошуку",
    notSearchable: "Недоступна в пошуку",
    generateError:
      "Не вдалося додати створення назв у чергу. Спробуйте ще раз.",
    generate: "Створити назви",
    decisionError:
      "Не вдалося застосувати рішення. Оновіть сторінку й повторіть спробу.",
    queuedFeedback: "Створення назв додано в чергу.",
    approvedFeedback: "Назву схвалено, переіндексацію пошуку додано в чергу.",
    rejectedFeedback: "Назву відхилено, до пошуку її не додано.",
    staleFeedback:
      "Ідентичність джерела змінилася. Оновіть дані перед новою перевіркою.",
    collisionFeedback:
      "Нормалізована назва належить іншій ідентичності. Нічого не опубліковано.",
    approve: "Схвалити назву",
    reject: "Відхилити назву",
    statuses: {
      generated: "Згенерований кандидат",
      review_needed: "Потрібна перевірка конфлікту",
      rejected: "Назву відхилено",
      accepted: "Прийнято · пошук під час введення",
    },
    reasons: {
      cyrtranslit_forward: "Пряма транслітерація CyrTranslit",
      cyrtranslit_reverse: "Зворотна транслітерація CyrTranslit",
      ru_yo_fold: "Російський варіант ё/е",
      uk_ghe_fold: "Український варіант ґ/г",
      normalized_collision: "Конфлікт нормалізованої назви",
    },
    decisions: {
      incorrect_variant: "Неправильний варіант",
      locale_or_script_mismatch: "Невідповідність локалі або письма",
      ambiguous_catalog_identity: "Неоднозначна ідентичність каталогу",
      unsafe_generated_form: "Небезпечна згенерована форма",
      other_review_reason: "Інша причина перевірки",
      rejected: "Відхилено",
    },
  },
  seedProof: {
    title: "Блоки доказів сорту",
    existing: "Наявні",
    plainText: "Звичайний текст",
    newProof: "Новий блок доказів",
    catalogItem: "Елемент каталогу",
    searchPlaceholder: "Пошук елемента каталогу",
    clearCatalogItem: "Очистити вибір елемента каталогу",
    save: "Зберегти доказ",
    update: "Оновити доказ",
    titleField: "Заголовок",
    summary: "Короткий опис",
    body: "Основний текст",
    sourceLabel: "Назва джерела",
    noSelection: "Елемент каталогу не вибрано",
  },
  sourceReview: {
    title: "Перевірка кандидатів із джерел",
    noCandidates: "Кандидатів із джерел, що очікують на перевірку, немає.",
    promote: "Опублікувати",
    hold: "Утримати",
    reject: "Відхилити",
    promotionBlocked: "Цей кандидат зараз не може бути опублікований.",
  },
  entity: {
    title: "QA розв'язання ідентичностей",
    refresh: "Оновити fuzzy QA",
    clusters: "Кластери",
    catalogRows: "Рядки каталогу",
    aliasChecks: "Перевірки назв",
    sourceGroups: "Групи джерел",
    fuzzyReviewed: "Fuzzy-перевірка: {reviewed} із {total}",
    leakCheck: "Перевірка витоку",
    noClusters:
      "У поточному безпечному звіті немає кластерів, які потребують перевірки.",
    score: "Оцінка",
    reasons: "Причини",
    reviewPath: "Перейти до перевірки",
    locale: "Локаль",
    sourceLinks: "Посилання на джерела",
    slug: "Slug",
    normalized: "Нормалізовано",
    clusterTitle: "{kind}: {count} пов'язаних рядків",
    clusterReason:
      "Перевірте наведені безпечні докази перед будь-якою зміною канонічної ідентичності.",
    groups: {
      fuzzy_duplicate: {
        label: "Fuzzy-дублікат",
        nextAction: "Перевірити об'єднання або утримати",
      },
      likely_duplicate: {
        label: "Ймовірний дублікат",
        nextAction: "Перевірити об'єднання",
      },
      source_disagreement: {
        label: "Розбіжність джерел",
        nextAction: "Перевірити пріоритет канонічного джерела",
      },
      alias_collision: {
        label: "Конфлікт назв",
        nextAction: "Утримати назву або об'єднати вручну",
      },
      manual_review_required: {
        label: "Потрібна ручна перевірка",
        nextAction: "Перевірити чергу кандидатів із джерел",
      },
      blocked_projection: {
        label: "Заблокована проєкція",
        nextAction: "Відхилити або залишити лише у джерелі",
      },
      canonical_concept: {
        label: "Канонічна концепція",
        nextAction: "Не виконувати руйнівних дій",
      },
    },
    riskLevels: {
      info: "Інформація",
      review_needed: "Потрібна перевірка",
      blocked: "Заблоковано",
    },
    actions: {
      merge_review: "Перевірка об'єднання",
      hold: "Утримати",
      reject: "Відхилити",
      review_needed: "Потрібна перевірка",
      no_action: "Без дій",
    },
    scoreBuckets: {
      high: "Висока схожість",
      medium: "Середня схожість",
      low: "Низька схожість",
    },
    localeRelations: {
      same_locale: "Одна локаль",
      cross_locale: "Різні локалі",
    },
    evidenceStatuses: {
      current: "Актуальні докази",
      stale: "Застарілі докази",
    },
    reasonCodes: {
      normalized_exact: "нормалізовані назви збігаються",
      cyrtranslit_exact: "ключі CyrTranslit збігаються",
      rapidfuzz_name_similarity: "схожість назв RapidFuzz",
      cross_script_similarity: "схожість між системами письма",
      same_catalog_kind: "однаковий тип каталогу",
      below_safe_threshold: "нижче безпечного порога",
      no_selectable_candidates: "немає кандидатів для вибору",
      unmatchable_input: "значення не можна безпечно зіставити",
    },
  },
  provenance: {
    title: "Походження імпортованих даних",
    noRows: "Походження імпортованих даних відсутнє.",
    row: "Рядок",
    auditLinks: "Посилання аудиту",
    aliasReviewStates: "Стани перевірки назв",
  },
  candidate: {
    noPending: "Кандидатів каталогу, що очікують, немає.",
    objects: "Об'єкти",
    created: "Створено",
    confirm: "Підтвердити",
    mergeTarget: "Ціль об'єднання",
    searchExisting: "Пошук наявного елемента каталогу",
    clearMergeTarget: "Очистити ціль об'єднання",
    target: "Ціль",
    noMergeTarget: "Ціль об'єднання не вибрано",
    merge: "Об'єднати",
    reject: "Відхилити",
    suggestionsTitle: "Детерміновані підказки зіставлення",
    suggestionsDescription:
      "Перевірте детерміновані докази перед зміною ідентичності каталогу. Відхилені докази зберігаються без зміни записів саду.",
    notEvaluated: "Ще не оцінено або очікується оновлення.",
    noSafeMatch: "Безпечного збігу в каталозі немає",
    rejectedMatch: "Відхилений збіг: {name}",
    heldMatch: "Утримано: {name}",
    suggestedTarget: "Запропонована ціль: {name}",
    canonical: "Канонічна назва",
    rejected: "Відхилено",
    normalized: "Нормалізовано",
    localeScript: "Локаль/письмо",
    reasons: "Причини",
    reviewReason: "Причина перевірки",
    reviewedUnchanged:
      "Перевірено {date}. Ідентичність каталогу та історію журналу не змінено.",
    refreshMatches: "Оновити зіставлення",
    decisionError:
      "Не вдалося застосувати рішення. Оновіть докази й повторіть спробу.",
    approvedFeedback:
      "Збіг схвалено, пов'язані об'єкти переведено на канонічну ідентичність.",
    rejectedFeedback: "Підказку відхилено, записи саду не змінено.",
    staleFeedback: "Підказка змінилася до перевірки. Нічого не застосовано.",
    approveMatch: "Схвалити збіг",
    rejectSuggestion: "Відхилити підказку",
    confidenceBuckets: {
      high: "Висока впевненість",
      medium: "Середня впевненість",
      low: "Низька впевненість",
      none: "Безпечної підказки немає",
    },
    matchTypes: {
      normalized_exact: "Точний збіг назви",
      transliteration_exact: "Збіг транслітерації",
      fuzzy_name: "Fuzzy-збіг назви",
      no_safe_match: "Утримано",
    },
    decisions: {
      approved_canonical_match: "Схвалений канонічний збіг",
      not_same_entity: "Неправильна ідентичність",
      wrong_catalog_kind: "Неправильний тип каталогу",
      locale_or_script_mismatch: "Невідповідність локалі або письма",
      insufficient_evidence: "Недостатньо доказів",
      other_review_reason: "Інша причина перевірки",
      legacy_review: "Попереднє рішення перевірки",
    },
  },
} as const;

export type OperatorCurationCopy = WidenCopy<typeof UK_COPY>;

const REGISTRY_UK_COPY = {
  metadataTitle: "Реєстр каталогу | OverGarden",
  metadataDescription:
    "Захищений операторський центр випусків для незмінного Stable Registry OverGarden.",
  title: "Stable Registry — Foundation",
  description:
    "Побудуйте один незмінний випуск із завершеного захоплення. Рішення приймаються лише для груп винятків; source-only дані не стають продуктом автоматично.",
  signInRequired: "Увійдіть, щоб відкрити центр випусків.",
  accessDenied: "Доступ до центру випусків заборонено.",
  releaseCenterDisabled:
    "Центр випусків ще не активований у цьому середовищі. Поточний каталог не змінено.",
  returnToCatalog: "Повернутися до поточного каталогу",
  summaryTitle: "Безпечне зведення",
  summaryDescription:
    "Показано лише агрегати класифікації. Не показуються raw source-поля, точні координати чи приватні ідентифікатори.",
  completedCaptures: "Завершені захоплення",
  releaseMembers: "Учасники випуску",
  exceptionGroups: "Групи винятків",
  productEligible: "Продуктово придатні",
  blockingGroups: "Блокувальні групи",
  releaseState: "Стан випуску",
  records: "Записів",
  buildFoundation: "Побудувати Foundation",
  buildQueued: "Побудову Foundation додано в чергу.",
  cancelBuild: "Скасувати побудову",
  cancelled: "Побудову скасовано. Поточний каталог не змінено.",
  noExceptionGroups: "Немає відкритих груп винятків.",
  decision: "Рішення для групи",
  saveDecision: "Зберегти рішення",
  decisionSaved: "Рішення збережено. Перегляньте оновлене зведення.",
  approvePreview: "Схвалити незмінний preview",
  previewApproved: "Preview схвалено. Він прив’язаний до поточних рішень.",
  activationConfirmation:
    "Активація перемикає лише локальний pointer випуску й ставить derived search у чергу. Публічний каталог не оголошується готовим тут.",
  activateFoundation: "Активувати локально",
  activated: "Локальний Foundation активовано; search intent додано в чергу.",
  releaseStates: {
    draft: "Чернетка",
    building: "Побудова",
    review_ready: "Готово до перевірки",
    approved: "Preview схвалено",
    active: "Локально активно",
    retired: "Замінено",
    failed: "Не завершено",
    abandoned: "Скасовано",
  },
  groupStates: {
    open: "Потрібне рішення",
    decided: "Рішення збережено",
    deferred: "Відкладено поза Foundation",
    blocked: "Заблоковано правилом",
  },
  outcomeLabels: {
    stale: "Стан змінився. Оновіть сторінку перед повторною дією.",
    blocked: "Дія заблокована поточним безпечним станом.",
    forbidden: "Доступ заборонено.",
    not_found: "Випуск або групу не знайдено.",
  },
  decisionLabels: {
    same_concept: "Це той самий концепт",
    different_concept: "Це різні концепти",
    add_alias: "Додати псевдонім",
    keep_current: "Залишити поточне",
    create_successor: "Створити наступника",
    defer: "Відкласти поза Foundation",
    block_rule: "Заблокувати правилом",
  },
  reasonLabels: {
    accepted_name_conflict: "Конфлікт прийнятої назви",
    rank_conflict: "Конфлікт рангу",
    ambiguous_identity: "Неоднозначна ідентичність",
    merge_candidate: "Кандидат на об’єднання",
    split_candidate: "Кандидат на поділ",
    rights_ambiguity: "Неясність прав",
    unsupported_field: "Непідтримуване поле",
    authority_corroboration_required: "Потрібне підтвердження authority",
    source_only_or_ineligible: "Лише source / не придатне до продукту",
  },
} as const;

export type StableRegistryCopy = WidenCopy<typeof REGISTRY_UK_COPY>;

const REGISTRY_BG_COPY = {
  metadataTitle: "Регистър на каталога | OverGarden",
  metadataDescription:
    "Защитен операторски център за издания на неизменяемия Stable Registry на OverGarden.",
  title: "Stable Registry — Foundation",
  description:
    "Създайте едно неизменяемо издание от завършено заснемане. Решенията са само за групи изключения; source-only данните не стават продукт автоматично.",
  signInRequired: "Влезте, за да отворите центъра за издания.",
  accessDenied: "Достъпът до центъра за издания е отказан.",
  releaseCenterDisabled:
    "Центърът за издания още не е включен в тази среда. Текущият каталог не е променен.",
  returnToCatalog: "Към текущия каталог",
  summaryTitle: "Безопасно обобщение",
  summaryDescription:
    "Показани са само агрегати на класификацията. Raw source полета, точни координати и лични идентификатори не се показват.",
  completedCaptures: "Завършени заснемания",
  releaseMembers: "Членове на изданието",
  exceptionGroups: "Групи изключения",
  productEligible: "Допустими за продукта",
  blockingGroups: "Блокиращи групи",
  releaseState: "Състояние на изданието",
  records: "Записи",
  buildFoundation: "Създай Foundation",
  buildQueued: "Създаването на Foundation е добавено в опашката.",
  cancelBuild: "Откажи създаването",
  cancelled: "Създаването е отменено. Текущият каталог не е променен.",
  noExceptionGroups: "Няма отворени групи изключения.",
  decision: "Решение за групата",
  saveDecision: "Запази решението",
  decisionSaved: "Решението е запазено. Прегледайте обновеното обобщение.",
  approvePreview: "Одобри неизменяем preview",
  previewApproved: "Preview е одобрен и е обвързан с текущите решения.",
  activationConfirmation:
    "Активирането сменя само локалния pointer на изданието и добавя derived search в опашката. Публичният каталог не се обявява за готов тук.",
  activateFoundation: "Активирай локално",
  activated:
    "Локалният Foundation е активиран; search intent е добавен в опашката.",
  releaseStates: {
    draft: "Чернова",
    building: "Създаване",
    review_ready: "Готово за проверка",
    approved: "Preview е одобрен",
    active: "Локално активно",
    retired: "Заменено",
    failed: "Неуспешно",
    abandoned: "Отменено",
  },
  groupStates: {
    open: "Нужно е решение",
    decided: "Решението е запазено",
    deferred: "Отложено извън Foundation",
    blocked: "Блокирано от правило",
  },
  outcomeLabels: {
    stale: "Състоянието е променено. Обновете страницата преди нов опит.",
    blocked: "Действието е блокирано от текущото безопасно състояние.",
    forbidden: "Достъпът е отказан.",
    not_found: "Изданието или групата не е намерена.",
  },
  decisionLabels: {
    same_concept: "Същият концепт",
    different_concept: "Различни концепти",
    add_alias: "Добави псевдоним",
    keep_current: "Запази текущото",
    create_successor: "Създай наследник",
    defer: "Отложи извън Foundation",
    block_rule: "Блокирай с правило",
  },
  reasonLabels: {
    accepted_name_conflict: "Конфликт на прието име",
    rank_conflict: "Конфликт на ранг",
    ambiguous_identity: "Нееднозначна идентичност",
    merge_candidate: "Кандидат за обединяване",
    split_candidate: "Кандидат за разделяне",
    rights_ambiguity: "Неясни права",
    unsupported_field: "Неподдържано поле",
    authority_corroboration_required: "Нужно е потвърждение на authority",
    source_only_or_ineligible: "Само source / недопустимо за продукта",
  },
} as const satisfies StableRegistryCopy;

const REGISTRY_RU_COPY = {
  metadataTitle: "Реестр каталога | OverGarden",
  metadataDescription:
    "Защищённый операторский центр выпусков неизменяемого Stable Registry OverGarden.",
  title: "Stable Registry — Foundation",
  description:
    "Соберите один неизменяемый выпуск из завершённого захвата. Решения нужны только для групп исключений; source-only данные не становятся продуктом автоматически.",
  signInRequired: "Войдите, чтобы открыть центр выпусков.",
  accessDenied: "Доступ к центру выпусков запрещён.",
  releaseCenterDisabled:
    "Центр выпусков ещё не включён в этой среде. Текущий каталог не изменён.",
  returnToCatalog: "Вернуться к текущему каталогу",
  summaryTitle: "Безопасная сводка",
  summaryDescription:
    "Показаны только агрегаты классификации. Raw source поля, точные координаты и личные идентификаторы не выводятся.",
  completedCaptures: "Завершённые захваты",
  releaseMembers: "Участники выпуска",
  exceptionGroups: "Группы исключений",
  productEligible: "Допустимые для продукта",
  blockingGroups: "Блокирующие группы",
  releaseState: "Состояние выпуска",
  records: "Записей",
  buildFoundation: "Собрать Foundation",
  buildQueued: "Сборка Foundation добавлена в очередь.",
  cancelBuild: "Отменить сборку",
  cancelled: "Сборка отменена. Текущий каталог не изменён.",
  noExceptionGroups: "Открытых групп исключений нет.",
  decision: "Решение по группе",
  saveDecision: "Сохранить решение",
  decisionSaved: "Решение сохранено. Проверьте обновлённую сводку.",
  approvePreview: "Одобрить неизменяемый preview",
  previewApproved: "Preview одобрен и привязан к текущим решениям.",
  activationConfirmation:
    "Активация переключает только локальный pointer выпуска и добавляет derived search в очередь. Публичный каталог здесь не объявляется готовым.",
  activateFoundation: "Активировать локально",
  activated:
    "Локальный Foundation активирован; search intent добавлен в очередь.",
  releaseStates: {
    draft: "Черновик",
    building: "Сборка",
    review_ready: "Готово к проверке",
    approved: "Preview одобрен",
    active: "Локально активно",
    retired: "Заменено",
    failed: "Не завершено",
    abandoned: "Отменено",
  },
  groupStates: {
    open: "Нужно решение",
    decided: "Решение сохранено",
    deferred: "Отложено вне Foundation",
    blocked: "Заблокировано правилом",
  },
  outcomeLabels: {
    stale: "Состояние изменилось. Обновите страницу перед повторной попыткой.",
    blocked: "Действие заблокировано текущим безопасным состоянием.",
    forbidden: "Доступ запрещён.",
    not_found: "Выпуск или группа не найдены.",
  },
  decisionLabels: {
    same_concept: "Тот же концепт",
    different_concept: "Разные концепты",
    add_alias: "Добавить псевдоним",
    keep_current: "Оставить текущее",
    create_successor: "Создать преемника",
    defer: "Отложить вне Foundation",
    block_rule: "Заблокировать правилом",
  },
  reasonLabels: {
    accepted_name_conflict: "Конфликт принятого имени",
    rank_conflict: "Конфликт ранга",
    ambiguous_identity: "Неоднозначная идентичность",
    merge_candidate: "Кандидат на объединение",
    split_candidate: "Кандидат на разделение",
    rights_ambiguity: "Неясность прав",
    unsupported_field: "Неподдерживаемое поле",
    authority_corroboration_required: "Нужно подтверждение authority",
    source_only_or_ineligible: "Только source / не подходит для продукта",
  },
} as const satisfies StableRegistryCopy;

const REGISTRY_COPY_BY_LOCALE = {
  uk: REGISTRY_UK_COPY,
  bg: REGISTRY_BG_COPY,
  ru: REGISTRY_RU_COPY,
} satisfies Record<InterfaceLocale, StableRegistryCopy>;

export function getStableRegistryCopy(
  locale: InterfaceLocale,
): StableRegistryCopy {
  return REGISTRY_COPY_BY_LOCALE[locale];
}

const BG_COPY = {
  page: {
    metadataTitle: "Куриране на каталога | OverGarden",
    metadataDescription:
      "Защитено операторско пространство за проверка на идентичности, източници и доказателства в каталога на OverGarden.",
    gardenJournal: "Дневник на градината",
    backToJournal: "Назад към дневника",
    title: "Куриране на каталога",
    accessDenied: "Достъпът е отказан.",
    pending: "Чакащи",
    seedProofs: "Блокове с доказателства",
    aliasReview: "Проверка на имената",
    sourceCandidates: "Кандидати от източници",
    sourceRows: "Редове от източници",
    gate: "Режим на достъп",
    sealedOwner: "защитен собственик",
    role: "Роля",
  },
  common: {
    rows: "Редове",
    all: "Всички",
    version: "Версия",
    unknown: "Неизвестно",
    source: "Източник",
    license: "Лиценз",
    parser: "Парсер",
    verified: "Проверено",
    fetched: "Получено",
    attribution: "Посочване на източника",
    attributionRequired: "изисква се посочване на източника",
    publicPage: "Публична страница",
    species: "Вид",
    candidateKind: "Тип кандидат",
    reviewNote: "Бележка от проверката",
    aliases: "имена",
    primary: "основно",
    typeahead: "търсене при въвеждане",
    typeaheadNames: "Имена за търсене",
    confidence: "Увереност",
    status: "Статус",
    updated: "Обновено",
    selected: "Избрано",
    searching: "Търсене...",
    suggestionsUnavailable: "Предложенията не са достъпни.",
    applying: "Прилагане...",
    queueing: "Добавяне в опашката...",
    refreshQueued: "Обновяването е добавено в опашката",
    rejectionReason: "Причина за отхвърляне",
    statuses: {
      quarantined: "Под карантина",
      held: "Задържано",
      review_needed: "Необходима е проверка",
      blocked: "Блокирано",
      rejected: "Отхвърлено",
      promoted: "Публикувано",
      provisional: "Предварително",
      seeded: "Начален каталог",
      confirmed: "Потвърдено",
      draft: "Чернова",
      published: "Публикувано",
      accepted: "Прието",
      generated: "Генерирано",
      current: "Актуално",
      stale: "Остаряло",
      passed: "Успешно",
    },
    catalogKinds: {
      plant_variety: "Сорт растение",
      species: "Вид",
      breed: "Порода",
      identity: "Идентичност в каталога",
    },
  },
  alias: {
    title: "Предложения за имена и езици",
    description:
      "Създавайте детерминирани варианти на изписване и транслитерация от потвърдена идентичност в каталога. Генериран ред достига търсенето само след изрично одобрение.",
    searchLabel: "Търсене на идентичност в каталога",
    searchPlaceholder: "Търсене на канонично или прието име",
    search: "Търсене",
    reviewQueue: "Опашка за проверка",
    noGenerated: "Все още няма генерирани предложения за имена.",
    searchPrompt: "Намерете идентичност в каталога, за да създадете варианти.",
    noMatches: "Няма глобални идентичности в каталога за това търсене.",
    acceptedNames: "Приети имена",
    generatedFrom: "генерирано от",
    collision:
      "Одобрението е блокирано, защото нормализираното име сочи към друга идентичност в каталога. Отстранете конфликта и генерирайте отново.",
    decision: "Решение",
    searchable: "Достъпно в търсенето",
    notSearchable: "Недостъпно в търсенето",
    generateError:
      "Генерирането на имена не можа да се добави в опашката. Опитайте отново.",
    generate: "Генериране на имена",
    decisionError:
      "Решението не можа да се приложи. Обновете страницата и опитайте отново.",
    queuedFeedback: "Генерирането на имена е добавено в опашката.",
    approvedFeedback:
      "Името е одобрено и преиндексирането на търсенето е добавено в опашката.",
    rejectedFeedback: "Името е отхвърлено и не е добавено към търсенето.",
    staleFeedback:
      "Идентичността на източника е променена. Обновете данните преди нова проверка.",
    collisionFeedback:
      "Нормализираното име принадлежи на друга идентичност. Нищо не е публикувано.",
    approve: "Одобряване на име",
    reject: "Отхвърляне на име",
    statuses: {
      generated: "Генериран кандидат",
      review_needed: "Необходима е проверка на конфликт",
      rejected: "Името е отхвърлено",
      accepted: "Прието · търсене при въвеждане",
    },
    reasons: {
      cyrtranslit_forward: "Права транслитерация с CyrTranslit",
      cyrtranslit_reverse: "Обратна транслитерация с CyrTranslit",
      ru_yo_fold: "Руски вариант ё/е",
      uk_ghe_fold: "Украински вариант ґ/г",
      normalized_collision: "Конфликт на нормализирано име",
    },
    decisions: {
      incorrect_variant: "Неправилен вариант",
      locale_or_script_mismatch: "Несъответствие на език или писменост",
      ambiguous_catalog_identity: "Нееднозначна идентичност в каталога",
      unsafe_generated_form: "Небезопасна генерирана форма",
      other_review_reason: "Друга причина за проверка",
      rejected: "Отхвърлено",
    },
  },
  seedProof: {
    title: "Блокове с доказателства за сорта",
    existing: "Съществуващи",
    plainText: "Обикновен текст",
    newProof: "Нов блок с доказателства",
    catalogItem: "Елемент от каталога",
    searchPlaceholder: "Търсене на елемент от каталога",
    clearCatalogItem: "Изчистване на избрания елемент от каталога",
    save: "Запазване на доказателството",
    update: "Обновяване на доказателството",
    titleField: "Заглавие",
    summary: "Кратко описание",
    body: "Основен текст",
    sourceLabel: "Име на източника",
    noSelection: "Не е избран елемент от каталога",
  },
  sourceReview: {
    title: "Проверка на кандидати от източници",
    noCandidates: "Няма кандидати от източници, които чакат проверка.",
    promote: "Публикуване",
    hold: "Задържане",
    reject: "Отхвърляне",
    promotionBlocked: "Този кандидат в момента не може да бъде публикуван.",
  },
  entity: {
    title: "QA за разрешаване на идентичности",
    refresh: "Обновяване на fuzzy QA",
    clusters: "Клъстери",
    catalogRows: "Редове в каталога",
    aliasChecks: "Проверки на имена",
    sourceGroups: "Групи източници",
    fuzzyReviewed: "Fuzzy проверка: {reviewed} от {total}",
    leakCheck: "Проверка за изтичане",
    noClusters:
      "В текущия безопасен отчет няма клъстери, които изискват проверка.",
    score: "Оценка",
    reasons: "Причини",
    reviewPath: "Към проверката",
    locale: "Език",
    sourceLinks: "Връзки към източници",
    slug: "Slug",
    normalized: "Нормализирано",
    clusterTitle: "{kind}: {count} свързани реда",
    clusterReason:
      "Проверете показаните безопасни доказателства преди промяна на каноничната идентичност.",
    groups: {
      fuzzy_duplicate: {
        label: "Fuzzy дубликат",
        nextAction: "Проверка за сливане или задържане",
      },
      likely_duplicate: {
        label: "Вероятен дубликат",
        nextAction: "Проверка за сливане",
      },
      source_disagreement: {
        label: "Разминаване между източници",
        nextAction: "Проверка на приоритета на каноничния източник",
      },
      alias_collision: {
        label: "Конфликт на имена",
        nextAction: "Задържане на името или ръчно сливане",
      },
      manual_review_required: {
        label: "Необходима е ръчна проверка",
        nextAction: "Проверка на опашката с кандидати от източници",
      },
      blocked_projection: {
        label: "Блокирана проекция",
        nextAction: "Отхвърляне или запазване само в източника",
      },
      canonical_concept: {
        label: "Канонична концепция",
        nextAction: "Без разрушителни действия",
      },
    },
    riskLevels: {
      info: "Информация",
      review_needed: "Необходима е проверка",
      blocked: "Блокирано",
    },
    actions: {
      merge_review: "Проверка за сливане",
      hold: "Задържане",
      reject: "Отхвърляне",
      review_needed: "Необходима е проверка",
      no_action: "Без действие",
    },
    scoreBuckets: {
      high: "Високо сходство",
      medium: "Средно сходство",
      low: "Ниско сходство",
    },
    localeRelations: {
      same_locale: "Един език",
      cross_locale: "Различни езици",
    },
    evidenceStatuses: {
      current: "Актуални доказателства",
      stale: "Остарели доказателства",
    },
    reasonCodes: {
      normalized_exact: "нормализираните имена съвпадат",
      cyrtranslit_exact: "ключовете на CyrTranslit съвпадат",
      rapidfuzz_name_similarity: "сходство на имената по RapidFuzz",
      cross_script_similarity: "сходство между писмености",
      same_catalog_kind: "еднакъв тип каталог",
      below_safe_threshold: "под безопасния праг",
      no_selectable_candidates: "няма кандидати за избор",
      unmatchable_input: "стойността не може да бъде безопасно съпоставена",
    },
  },
  provenance: {
    title: "Произход на импортираните данни",
    noRows: "Няма данни за произхода на импортираните редове.",
    row: "Ред",
    auditLinks: "Връзки за одит",
    aliasReviewStates: "Състояния на проверката на имената",
  },
  candidate: {
    noPending: "Няма чакащи кандидати за каталога.",
    objects: "Обекти",
    created: "Създадено",
    confirm: "Потвърждаване",
    mergeTarget: "Цел за сливане",
    searchExisting: "Търсене на съществуващ елемент в каталога",
    clearMergeTarget: "Изчистване на целта за сливане",
    target: "Цел",
    noMergeTarget: "Не е избрана цел за сливане",
    merge: "Сливане",
    reject: "Отхвърляне",
    suggestionsTitle: "Детерминирани предложения за съпоставяне",
    suggestionsDescription:
      "Проверете детерминираните доказателства преди промяна на идентичността в каталога. Отхвърлените доказателства остават записани, без да променят данните на градината.",
    notEvaluated: "Все още не е оценено или обновяването се изчаква.",
    noSafeMatch: "Няма безопасно съвпадение в каталога",
    rejectedMatch: "Отхвърлено съвпадение: {name}",
    heldMatch: "Задържано: {name}",
    suggestedTarget: "Предложена цел: {name}",
    canonical: "Канонично име",
    rejected: "Отхвърлено",
    normalized: "Нормализирано",
    localeScript: "Език/писменост",
    reasons: "Причини",
    reviewReason: "Причина за проверка",
    reviewedUnchanged:
      "Проверено {date}. Идентичността в каталога и историята на дневника не са променени.",
    refreshMatches: "Обновяване на съпоставянията",
    decisionError:
      "Решението не можа да се приложи. Обновете доказателствата и опитайте отново.",
    approvedFeedback:
      "Съвпадението е одобрено и свързаните обекти използват каноничната идентичност.",
    rejectedFeedback:
      "Предложението е отхвърлено и данните на градината не са променени.",
    staleFeedback:
      "Предложението се е променило преди проверката. Нищо не е приложено.",
    approveMatch: "Одобряване на съвпадението",
    rejectSuggestion: "Отхвърляне на предложението",
    confidenceBuckets: {
      high: "Висока увереност",
      medium: "Средна увереност",
      low: "Ниска увереност",
      none: "Няма безопасно предложение",
    },
    matchTypes: {
      normalized_exact: "Точно съвпадение на име",
      transliteration_exact: "Съвпадение на транслитерация",
      fuzzy_name: "Fuzzy съвпадение на име",
      no_safe_match: "Задържано",
    },
    decisions: {
      approved_canonical_match: "Одобрено канонично съвпадение",
      not_same_entity: "Неправилна идентичност",
      wrong_catalog_kind: "Неправилен тип каталог",
      locale_or_script_mismatch: "Несъответствие на език или писменост",
      insufficient_evidence: "Недостатъчни доказателства",
      other_review_reason: "Друга причина за проверка",
      legacy_review: "Предишно решение от проверка",
    },
  },
} as const satisfies OperatorCurationCopy;

const RU_COPY = {
  page: {
    metadataTitle: "Курация каталога | OverGarden",
    metadataDescription:
      "Защищённое операторское пространство для проверки идентичностей, источников и доказательств каталога OverGarden.",
    gardenJournal: "Журнал сада",
    backToJournal: "Назад к журналу",
    title: "Курация каталога",
    accessDenied: "Доступ запрещён.",
    pending: "Ожидают",
    seedProofs: "Блоки доказательств",
    aliasReview: "Проверка названий",
    sourceCandidates: "Кандидаты из источников",
    sourceRows: "Строки источников",
    gate: "Режим доступа",
    sealedOwner: "защищённый владелец",
    role: "Роль",
  },
  common: {
    rows: "Строки",
    all: "Все",
    version: "Версия",
    unknown: "Неизвестно",
    source: "Источник",
    license: "Лицензия",
    parser: "Парсер",
    verified: "Проверено",
    fetched: "Получено",
    attribution: "Атрибуция",
    attributionRequired: "требуется атрибуция",
    publicPage: "Публичная страница",
    species: "Вид",
    candidateKind: "Тип кандидата",
    reviewNote: "Примечание проверки",
    aliases: "названий",
    primary: "основное",
    typeahead: "поиск при вводе",
    typeaheadNames: "Названия для поиска",
    confidence: "Уверенность",
    status: "Статус",
    updated: "Обновлено",
    selected: "Выбрано",
    searching: "Поиск...",
    suggestionsUnavailable: "Подсказки недоступны.",
    applying: "Применение...",
    queueing: "Добавление в очередь...",
    refreshQueued: "Обновление добавлено в очередь",
    rejectionReason: "Причина отклонения",
    statuses: {
      quarantined: "На карантине",
      held: "Удержано",
      review_needed: "Требуется проверка",
      blocked: "Заблокировано",
      rejected: "Отклонено",
      promoted: "Опубликовано",
      provisional: "Предварительное",
      seeded: "Начальный каталог",
      confirmed: "Подтверждено",
      draft: "Черновик",
      published: "Опубликовано",
      accepted: "Принято",
      generated: "Сгенерировано",
      current: "Актуально",
      stale: "Устарело",
      passed: "Пройдено",
    },
    catalogKinds: {
      plant_variety: "Сорт растения",
      species: "Вид",
      breed: "Порода",
      identity: "Идентичность каталога",
    },
  },
  alias: {
    title: "Подсказки названий и локалей",
    description:
      "Создавайте детерминированные варианты написания и транслитерации из подтверждённой идентичности каталога. Сгенерированная строка попадает в поиск только после явного одобрения.",
    searchLabel: "Поиск идентичности каталога",
    searchPlaceholder: "Поиск канонического или принятого названия",
    search: "Искать",
    reviewQueue: "Очередь проверки",
    noGenerated: "Сгенерированных подсказок названий пока нет.",
    searchPrompt: "Найдите идентичность каталога, чтобы создать варианты.",
    noMatches: "Глобальные идентичности каталога по этому запросу не найдены.",
    acceptedNames: "Принятых названий",
    generatedFrom: "создано из",
    collision:
      "Одобрение заблокировано, потому что нормализованное название ведёт к другой идентичности каталога. Устраните конфликт и создайте варианты повторно.",
    decision: "Решение",
    searchable: "Доступно в поиске",
    notSearchable: "Недоступно в поиске",
    generateError:
      "Не удалось добавить создание названий в очередь. Повторите попытку.",
    generate: "Создать названия",
    decisionError:
      "Не удалось применить решение. Обновите страницу и повторите попытку.",
    queuedFeedback: "Создание названий добавлено в очередь.",
    approvedFeedback:
      "Название одобрено, переиндексация поиска добавлена в очередь.",
    rejectedFeedback: "Название отклонено и не добавлено в поиск.",
    staleFeedback:
      "Идентичность источника изменилась. Обновите данные перед новой проверкой.",
    collisionFeedback:
      "Нормализованное название принадлежит другой идентичности. Ничего не опубликовано.",
    approve: "Одобрить название",
    reject: "Отклонить название",
    statuses: {
      generated: "Сгенерированный кандидат",
      review_needed: "Требуется проверка конфликта",
      rejected: "Название отклонено",
      accepted: "Принято · поиск при вводе",
    },
    reasons: {
      cyrtranslit_forward: "Прямая транслитерация CyrTranslit",
      cyrtranslit_reverse: "Обратная транслитерация CyrTranslit",
      ru_yo_fold: "Русский вариант ё/е",
      uk_ghe_fold: "Украинский вариант ґ/г",
      normalized_collision: "Конфликт нормализованного названия",
    },
    decisions: {
      incorrect_variant: "Неправильный вариант",
      locale_or_script_mismatch: "Несоответствие локали или письменности",
      ambiguous_catalog_identity: "Неоднозначная идентичность каталога",
      unsafe_generated_form: "Небезопасная сгенерированная форма",
      other_review_reason: "Другая причина проверки",
      rejected: "Отклонено",
    },
  },
  seedProof: {
    title: "Блоки доказательств сорта",
    existing: "Существующие",
    plainText: "Обычный текст",
    newProof: "Новый блок доказательств",
    catalogItem: "Элемент каталога",
    searchPlaceholder: "Поиск элемента каталога",
    clearCatalogItem: "Очистить выбор элемента каталога",
    save: "Сохранить доказательство",
    update: "Обновить доказательство",
    titleField: "Заголовок",
    summary: "Краткое описание",
    body: "Основной текст",
    sourceLabel: "Название источника",
    noSelection: "Элемент каталога не выбран",
  },
  sourceReview: {
    title: "Проверка кандидатов из источников",
    noCandidates: "Нет кандидатов из источников, ожидающих проверки.",
    promote: "Опубликовать",
    hold: "Удержать",
    reject: "Отклонить",
    promotionBlocked: "Этот кандидат сейчас не может быть опубликован.",
  },
  entity: {
    title: "QA разрешения идентичностей",
    refresh: "Обновить fuzzy QA",
    clusters: "Кластеры",
    catalogRows: "Строки каталога",
    aliasChecks: "Проверки названий",
    sourceGroups: "Группы источников",
    fuzzyReviewed: "Fuzzy-проверка: {reviewed} из {total}",
    leakCheck: "Проверка утечки",
    noClusters:
      "В текущем безопасном отчёте нет кластеров, требующих проверки.",
    score: "Оценка",
    reasons: "Причины",
    reviewPath: "Перейти к проверке",
    locale: "Локаль",
    sourceLinks: "Ссылки на источники",
    slug: "Slug",
    normalized: "Нормализовано",
    clusterTitle: "{kind}: {count} связанных строк",
    clusterReason:
      "Проверьте показанные безопасные доказательства перед изменением канонической идентичности.",
    groups: {
      fuzzy_duplicate: {
        label: "Fuzzy-дубликат",
        nextAction: "Проверить объединение или удержать",
      },
      likely_duplicate: {
        label: "Вероятный дубликат",
        nextAction: "Проверить объединение",
      },
      source_disagreement: {
        label: "Расхождение источников",
        nextAction: "Проверить приоритет канонического источника",
      },
      alias_collision: {
        label: "Конфликт названий",
        nextAction: "Удержать название или объединить вручную",
      },
      manual_review_required: {
        label: "Требуется ручная проверка",
        nextAction: "Проверить очередь кандидатов из источников",
      },
      blocked_projection: {
        label: "Заблокированная проекция",
        nextAction: "Отклонить или оставить только в источнике",
      },
      canonical_concept: {
        label: "Каноническая концепция",
        nextAction: "Не выполнять разрушительных действий",
      },
    },
    riskLevels: {
      info: "Информация",
      review_needed: "Требуется проверка",
      blocked: "Заблокировано",
    },
    actions: {
      merge_review: "Проверка объединения",
      hold: "Удержать",
      reject: "Отклонить",
      review_needed: "Требуется проверка",
      no_action: "Без действий",
    },
    scoreBuckets: {
      high: "Высокое сходство",
      medium: "Среднее сходство",
      low: "Низкое сходство",
    },
    localeRelations: {
      same_locale: "Одна локаль",
      cross_locale: "Разные локали",
    },
    evidenceStatuses: {
      current: "Актуальные доказательства",
      stale: "Устаревшие доказательства",
    },
    reasonCodes: {
      normalized_exact: "нормализованные названия совпадают",
      cyrtranslit_exact: "ключи CyrTranslit совпадают",
      rapidfuzz_name_similarity: "сходство названий RapidFuzz",
      cross_script_similarity: "сходство между системами письма",
      same_catalog_kind: "одинаковый тип каталога",
      below_safe_threshold: "ниже безопасного порога",
      no_selectable_candidates: "нет кандидатов для выбора",
      unmatchable_input: "значение нельзя безопасно сопоставить",
    },
  },
  provenance: {
    title: "Происхождение импортированных данных",
    noRows: "Происхождение импортированных данных отсутствует.",
    row: "Строка",
    auditLinks: "Ссылки аудита",
    aliasReviewStates: "Состояния проверки названий",
  },
  candidate: {
    noPending: "Нет ожидающих кандидатов каталога.",
    objects: "Объекты",
    created: "Создано",
    confirm: "Подтвердить",
    mergeTarget: "Цель объединения",
    searchExisting: "Поиск существующего элемента каталога",
    clearMergeTarget: "Очистить цель объединения",
    target: "Цель",
    noMergeTarget: "Цель объединения не выбрана",
    merge: "Объединить",
    reject: "Отклонить",
    suggestionsTitle: "Детерминированные подсказки сопоставления",
    suggestionsDescription:
      "Проверьте детерминированные доказательства перед изменением идентичности каталога. Отклонённые доказательства сохраняются без изменения данных сада.",
    notEvaluated: "Ещё не оценено или ожидается обновление.",
    noSafeMatch: "Безопасного совпадения в каталоге нет",
    rejectedMatch: "Отклонённое совпадение: {name}",
    heldMatch: "Удержано: {name}",
    suggestedTarget: "Предложенная цель: {name}",
    canonical: "Каноническое название",
    rejected: "Отклонено",
    normalized: "Нормализовано",
    localeScript: "Локаль/письменность",
    reasons: "Причины",
    reviewReason: "Причина проверки",
    reviewedUnchanged:
      "Проверено {date}. Идентичность каталога и история журнала не изменены.",
    refreshMatches: "Обновить сопоставления",
    decisionError:
      "Не удалось применить решение. Обновите доказательства и повторите попытку.",
    approvedFeedback:
      "Совпадение одобрено, связанные объекты переведены на каноническую идентичность.",
    rejectedFeedback: "Подсказка отклонена, данные сада не изменены.",
    staleFeedback: "Подсказка изменилась до проверки. Ничего не применено.",
    approveMatch: "Одобрить совпадение",
    rejectSuggestion: "Отклонить подсказку",
    confidenceBuckets: {
      high: "Высокая уверенность",
      medium: "Средняя уверенность",
      low: "Низкая уверенность",
      none: "Безопасной подсказки нет",
    },
    matchTypes: {
      normalized_exact: "Точное совпадение названия",
      transliteration_exact: "Совпадение транслитерации",
      fuzzy_name: "Fuzzy-совпадение названия",
      no_safe_match: "Удержано",
    },
    decisions: {
      approved_canonical_match: "Одобренное каноническое совпадение",
      not_same_entity: "Неправильная идентичность",
      wrong_catalog_kind: "Неправильный тип каталога",
      locale_or_script_mismatch: "Несоответствие локали или письменности",
      insufficient_evidence: "Недостаточно доказательств",
      other_review_reason: "Другая причина проверки",
      legacy_review: "Предыдущее решение проверки",
    },
  },
} as const satisfies OperatorCurationCopy;

const COPY_BY_LOCALE = {
  uk: UK_COPY,
  bg: BG_COPY,
  ru: RU_COPY,
} satisfies Record<InterfaceLocale, OperatorCurationCopy>;

export function getOperatorCurationCopy(
  locale: InterfaceLocale,
): OperatorCurationCopy {
  return COPY_BY_LOCALE[locale];
}

export function operatorCurationMapLabel(
  values: Readonly<Record<string, string>>,
  value: string | null | undefined,
  fallback: string,
) {
  return value ? (values[value] ?? value) : fallback;
}
