import type { InterfaceLocale } from "@/lib/interface-localization";

const PUBLIC_PROFILE_COPY = {
  uk: {
    profileLabel: "Профіль садівника",
    metadataSuffix: "публічний профіль",
    objectsTitle: "Живі об’єкти",
    objectsDescription:
      "Рослини, тварини та бджолині сім’ї з відкритою історією догляду.",
    journalsTitle: "Журнал догляду",
    journalsDescription: "Опубліковані спостереження, зміни та результати.",
    aboutTitle: "Про садівника",
    aboutEmpty: "Автор поки не додав опис.",
    follow: "Стежити",
    unfollow: "Не стежити",
    followingState: "Ви стежите",
    report: "Поскаржитися",
    block: "Заблокувати",
    moreActions: "Інші дії",
    manageProfile: "Редагувати профіль",
    addFirstObject: "Додати перший об’єкт",
    publicObjects: "Об’єкти",
    publicEntries: "Записи",
    followers: "Стежать",
    following: "Стежить",
    lineage: "Підтверджені походження",
    plants: "Рослини",
    animals: "Тварини",
    noObjects: "Публічних об’єктів ще немає.",
    noOwnerObjects:
      "Додайте живий об’єкт і опублікуйте перший запис, щоб він з’явився тут.",
    noJournals: "Опублікованих записів ще немає.",
    noOwnerJournals:
      "Опублікуйте запис про об’єкт або простір, щоб почати журнал.",
    showMore: (count: number, hasMore: boolean) =>
      `Показати ще ${count}${hasMore ? "+" : ""}`,
    entryCount: (count: number) => `${count} зап.`,
    latestUpdate: "Оновлено",
    identityConfirmed: "Визначено",
    identityProvisional: "Уточнюється",
    identityUnknown: "Без визначення",
    region: "Регіон",
    languages: "Мови",
    activity: "Активність",
    navigation: "Перейти далі",
    followedFeed: "Стрічка підписок",
    lineageClaims: "Запити походження",
    relationshipsHidden: "Лічильники підписок приховані.",
    reportTitle: "Причина скарги",
    reportSubmit: "Надіслати скаргу",
    reportReasons: {
      spam: "Спам",
      harassment: "Переслідування",
      privacy: "Порушення приватності",
      impersonation: "Видає себе за іншу особу",
      other: "Інше",
    },
    privateProfile: "Приватний профіль",
    actionMessages: {
      followed: "Тепер ви стежите за цим профілем.",
      unfollowed: "Ви більше не стежите за цим профілем.",
      reported: "Скаргу прийнято.",
      unavailable: "Дію не виконано. Оновіть сторінку та спробуйте ще раз.",
    },
  },
  bg: {
    profileLabel: "Профил на градинар",
    metadataSuffix: "публичен профил",
    objectsTitle: "Живи обекти",
    objectsDescription:
      "Растения, животни и пчелни семейства с публична история на грижите.",
    journalsTitle: "Дневник за грижи",
    journalsDescription: "Публикувани наблюдения, промени и резултати.",
    aboutTitle: "За градинаря",
    aboutEmpty: "Авторът все още не е добавил описание.",
    follow: "Следвай",
    unfollow: "Спри следването",
    followingState: "Следвате",
    report: "Докладвай",
    block: "Блокирай",
    moreActions: "Други действия",
    manageProfile: "Редактирай профила",
    addFirstObject: "Добави първи обект",
    publicObjects: "Обекти",
    publicEntries: "Записи",
    followers: "Последователи",
    following: "Следва",
    lineage: "Потвърден произход",
    plants: "Растения",
    animals: "Животни",
    noObjects: "Все още няма публични обекти.",
    noOwnerObjects:
      "Добавете жив обект и публикувайте първия запис, за да се появи тук.",
    noJournals: "Все още няма публикувани записи.",
    noOwnerJournals:
      "Публикувайте запис за обект или пространство, за да започнете дневника.",
    showMore: (count: number, hasMore: boolean) =>
      `Покажи още ${count}${hasMore ? "+" : ""}`,
    entryCount: (count: number) => `${count} зап.`,
    latestUpdate: "Обновено",
    identityConfirmed: "Определено",
    identityProvisional: "Уточнява се",
    identityUnknown: "Без определяне",
    region: "Регион",
    languages: "Езици",
    activity: "Активност",
    navigation: "Продължете към",
    followedFeed: "Поток от следвани",
    lineageClaims: "Заявки за произход",
    relationshipsHidden: "Броячите за следване са скрити.",
    reportTitle: "Причина за доклада",
    reportSubmit: "Изпрати доклад",
    reportReasons: {
      spam: "Спам",
      harassment: "Тормоз",
      privacy: "Нарушение на поверителността",
      impersonation: "Представяне за друго лице",
      other: "Друго",
    },
    privateProfile: "Частен профил",
    actionMessages: {
      followed: "Вече следвате този профил.",
      unfollowed: "Вече не следвате този профил.",
      reported: "Докладът е приет.",
      unavailable:
        "Действието не бе изпълнено. Обновете страницата и опитайте пак.",
    },
  },
  ru: {
    profileLabel: "Профиль садовода",
    metadataSuffix: "публичный профиль",
    objectsTitle: "Живые объекты",
    objectsDescription:
      "Растения, животные и пчелиные семьи с открытой историей ухода.",
    journalsTitle: "Журнал ухода",
    journalsDescription: "Опубликованные наблюдения, изменения и результаты.",
    aboutTitle: "О садоводе",
    aboutEmpty: "Автор пока не добавил описание.",
    follow: "Следить",
    unfollow: "Не следить",
    followingState: "Вы следите",
    report: "Пожаловаться",
    block: "Заблокировать",
    moreActions: "Другие действия",
    manageProfile: "Редактировать профиль",
    addFirstObject: "Добавить первый объект",
    publicObjects: "Объекты",
    publicEntries: "Записи",
    followers: "Следят",
    following: "Следит",
    lineage: "Подтверждённое происхождение",
    plants: "Растения",
    animals: "Животные",
    noObjects: "Публичных объектов пока нет.",
    noOwnerObjects:
      "Добавьте живой объект и опубликуйте первую запись, чтобы он появился здесь.",
    noJournals: "Опубликованных записей пока нет.",
    noOwnerJournals:
      "Опубликуйте запись об объекте или пространстве, чтобы начать журнал.",
    showMore: (count: number, hasMore: boolean) =>
      `Показать ещё ${count}${hasMore ? "+" : ""}`,
    entryCount: (count: number) => `${count} зап.`,
    latestUpdate: "Обновлено",
    identityConfirmed: "Определено",
    identityProvisional: "Уточняется",
    identityUnknown: "Без определения",
    region: "Регион",
    languages: "Языки",
    activity: "Активность",
    navigation: "Перейти дальше",
    followedFeed: "Лента подписок",
    lineageClaims: "Запросы происхождения",
    relationshipsHidden: "Счётчики подписок скрыты.",
    reportTitle: "Причина жалобы",
    reportSubmit: "Отправить жалобу",
    reportReasons: {
      spam: "Спам",
      harassment: "Преследование",
      privacy: "Нарушение приватности",
      impersonation: "Выдаёт себя за другого человека",
      other: "Другое",
    },
    privateProfile: "Приватный профиль",
    actionMessages: {
      followed: "Теперь вы следите за этим профилем.",
      unfollowed: "Вы больше не следите за этим профилем.",
      reported: "Жалоба принята.",
      unavailable:
        "Действие не выполнено. Обновите страницу и попробуйте снова.",
    },
  },
} satisfies Record<InterfaceLocale, object>;

export function getPublicProfileCopy(locale: InterfaceLocale) {
  return PUBLIC_PROFILE_COPY[locale];
}

export const PUBLIC_PROFILE_LANGUAGE_LABELS: Record<
  InterfaceLocale,
  Record<"uk" | "bg" | "ru" | "en", string>
> = {
  uk: { uk: "Українська", bg: "Български", ru: "Російська", en: "English" },
  bg: { uk: "Українська", bg: "Български", ru: "Русский", en: "English" },
  ru: { uk: "Українська", bg: "Български", ru: "Русский", en: "English" },
};
