import type { StructuredJournalComposerLabels } from "@/components/garden/structured-journal-composer";
import type { PublicLocale } from "@/lib/public-localization";

const LABELS: Record<PublicLocale, StructuredJournalComposerLabels> = {
  uk: {
    loading: "Завантаження редактора…",
    failureTitle: "Редактор тимчасово недоступний",
    failureBody:
      "Чернетку збережено. Оновіть сторінку, щоб продовжити без втрати тексту й фото.",
    retry: "Спробувати знову",
    silentLoss:
      "Збереження зупинено: частина блоку зникла під час серіалізації.",
    imageChoose: "Додати фото",
    imageUploading: "Обробка фото…",
    imageFailed: "Фото не вдалося підготувати. Запис ще не опубліковано.",
    imageTooLarge: "Фото завелике. Оберіть фото до 50 MiB.",
    imageUnsupported: "Оберіть фото JPEG, PNG, WebP або HEIC.",
    imageRetry: "Повторити фото",
    imageReplace: "Замінити фото",
    imageSetCover: "Використати як обкладинку",
    imageCaption: "Підпис до фото",
    imageCaptionPlaceholder: "Що на фото — одним реченням",
    imageRemove: "Прибрати фото",
    imageRejectRemote:
      "Можна лише файл з пристрою. Посилання й віддалені зображення відхилено.",
    unavailableTitle: "Вміст недоступний",
    unavailableBody: "Цей запис не вдалося безпечно показати.",
    titleLabel: "Заголовок",
    dateLabel: "Дата",
    saveLabel: "Зберегти",
    tools: {
      toolbar: "Форматування виділеного",
      editor: "Вміст запису",
      bold: "Жирний",
      italic: "Курсив",
      underline: "Підкреслений",
      strikethrough: "Закреслений",
      code: "Моноширинний",
      link: "Посилання",
      applyLink: "Застосувати",
      cancelLink: "Скасувати",
      quoteAttribution: "Додати автора цитати",
      removeQuoteAttribution: "Прибрати автора цитати",
    },
    reorder: {
      moveUp: "Перемістити вгору",
      moveDown: "Перемістити вниз",
      dragHandle: "Перетягнути блок",
      deleteBlock: "Видалити",
      movedAnnouncement: "{type} переміщено на позицію {position} з {total}",
      deletedAnnouncement: "Блок видалено: {type}",
      blockType: {
        paragraph: "Текст",
        header: "Заголовок",
        list: "Список",
        quote: "Цитата",
        callout: "Виноска",
        code: "Код",
        delimiter: "Роздільник",
        image: "Фото",
        unknown: "Блок",
      },
    },
    blocks: {
      add: "Додати блок",
      menu: "Дії з блоком",
      turnInto: "Перетворити на",
      duplicate: "Дублювати",
      duplicatedAnnouncement: "Блок продубльовано: {type}",
      noResults: "Нічого не знайдено",
      placeholder: "Напишіть щось або натисніть «/» для команд",
      placeholderFirst: "Як минув день у саду? Натисніть «/» для команд",
      commands: {
        paragraph: "Текст",
        heading1: "Заголовок 1",
        heading2: "Заголовок 2",
        heading3: "Заголовок 3",
        bulletList: "Маркований список",
        numberList: "Нумерований список",
        todoList: "Список завдань",
        quote: "Цитата",
        callout: "Виноска",
        code: "Код",
        delimiter: "Роздільник",
        image: "Фото",
      },
    },
  },
  bg: {
    loading: "Зареждане на редактора…",
    failureTitle: "Редакторът временно не е наличен",
    failureBody:
      "Черновата е запазена. Обновете страницата, за да продължите без загуба на текст и снимки.",
    retry: "Опитай отново",
    silentLoss: "Записът е спрян: част от блок изчезна при сериализация.",
    imageChoose: "Добави снимка",
    imageUploading: "Обработка на снимка…",
    imageFailed:
      "Снимката не можа да бъде подготвена. Записът не е публикуван.",
    imageTooLarge: "Снимката е твърде голяма. Изберете снимка до 50 MiB.",
    imageUnsupported: "Изберете снимка JPEG, PNG, WebP или HEIC.",
    imageRetry: "Опитай снимката отново",
    imageReplace: "Замени снимката",
    imageSetCover: "Използвай за корица",
    imageCaption: "Надпис към снимката",
    imageCaptionPlaceholder: "Какво се вижда — с едно изречение",
    imageRemove: "Премахни снимка",
    imageRejectRemote:
      "Само файл от устройството. Връзки и отдалечени изображения са отхвърлени.",
    unavailableTitle: "Съдържанието е недостъпно",
    unavailableBody: "Този запис не може да бъде показан безопасно.",
    titleLabel: "Заглавие",
    dateLabel: "Дата",
    saveLabel: "Запази",
    tools: {
      toolbar: "Форматиране на избраното",
      editor: "Съдържание на записа",
      bold: "Удебелен",
      italic: "Курсив",
      underline: "Подчертан",
      strikethrough: "Зачертан",
      code: "Равноширок",
      link: "Връзка",
      applyLink: "Приложи",
      cancelLink: "Отказ",
      quoteAttribution: "Добави автор на цитата",
      removeQuoteAttribution: "Премахни автора на цитата",
    },
    reorder: {
      moveUp: "Премести нагоре",
      moveDown: "Премести надолу",
      dragHandle: "Плъзни блок",
      deleteBlock: "Изтрий",
      movedAnnouncement: "{type} е преместен на позиция {position} от {total}",
      deletedAnnouncement: "Блокът е изтрит: {type}",
      blockType: {
        paragraph: "Текст",
        header: "Заглавие",
        list: "Списък",
        quote: "Цитат",
        callout: "Каре",
        code: "Код",
        delimiter: "Разделител",
        image: "Снимка",
        unknown: "Блок",
      },
    },
    blocks: {
      add: "Добави блок",
      menu: "Действия с блока",
      turnInto: "Преобразувай в",
      duplicate: "Дублирай",
      duplicatedAnnouncement: "Блокът е дублиран: {type}",
      noResults: "Нищо не е намерено",
      placeholder: "Напишете нещо или натиснете «/» за команди",
      placeholderFirst: "Как мина денят в градината? Натиснете «/» за команди",
      commands: {
        paragraph: "Текст",
        heading1: "Заглавие 1",
        heading2: "Заглавие 2",
        heading3: "Заглавие 3",
        bulletList: "Неподреден списък",
        numberList: "Подреден списък",
        todoList: "Списък със задачи",
        quote: "Цитат",
        callout: "Каре",
        code: "Код",
        delimiter: "Разделител",
        image: "Снимка",
      },
    },
  },
  ru: {
    loading: "Загрузка редактора…",
    failureTitle: "Редактор временно недоступен",
    failureBody:
      "Черновик сохранён. Обновите страницу, чтобы продолжить без потери текста и фото.",
    retry: "Попробовать снова",
    silentLoss: "Сохранение остановлено: часть блока исчезла при сериализации.",
    imageChoose: "Добавить фото",
    imageUploading: "Обработка фото…",
    imageFailed: "Фото не удалось подготовить. Запись ещё не опубликована.",
    imageTooLarge: "Фото слишком большое. Выберите фото до 50 MiB.",
    imageUnsupported: "Выберите фото JPEG, PNG, WebP или HEIC.",
    imageRetry: "Повторить фото",
    imageReplace: "Заменить фото",
    imageSetCover: "Использовать как обложку",
    imageCaption: "Подпись к фото",
    imageCaptionPlaceholder: "Что на фото — одним предложением",
    imageRemove: "Убрать фото",
    imageRejectRemote:
      "Только файл с устройства. Ссылки и удалённые изображения отклонены.",
    unavailableTitle: "Содержимое недоступно",
    unavailableBody: "Эту запись нельзя безопасно показать.",
    titleLabel: "Заголовок",
    dateLabel: "Дата",
    saveLabel: "Сохранить",
    tools: {
      toolbar: "Форматирование выделенного",
      editor: "Содержимое записи",
      bold: "Жирный",
      italic: "Курсив",
      underline: "Подчёркнутый",
      strikethrough: "Зачёркнутый",
      code: "Моноширинный",
      link: "Ссылка",
      applyLink: "Применить",
      cancelLink: "Отмена",
      quoteAttribution: "Добавить автора цитаты",
      removeQuoteAttribution: "Убрать автора цитаты",
    },
    reorder: {
      moveUp: "Переместить вверх",
      moveDown: "Переместить вниз",
      dragHandle: "Перетащить блок",
      deleteBlock: "Удалить",
      movedAnnouncement: "{type} перемещён на позицию {position} из {total}",
      deletedAnnouncement: "Блок удалён: {type}",
      blockType: {
        paragraph: "Текст",
        header: "Заголовок",
        list: "Список",
        quote: "Цитата",
        callout: "Выноска",
        code: "Код",
        delimiter: "Разделитель",
        image: "Фото",
        unknown: "Блок",
      },
    },
    blocks: {
      add: "Добавить блок",
      menu: "Действия с блоком",
      turnInto: "Преобразовать в",
      duplicate: "Дублировать",
      duplicatedAnnouncement: "Блок продублирован: {type}",
      noResults: "Ничего не найдено",
      placeholder: "Напишите что-нибудь или нажмите «/» для команд",
      placeholderFirst: "Как прошёл день в саду? Нажмите «/» для команд",
      commands: {
        paragraph: "Текст",
        heading1: "Заголовок 1",
        heading2: "Заголовок 2",
        heading3: "Заголовок 3",
        bulletList: "Маркированный список",
        numberList: "Нумерованный список",
        todoList: "Список задач",
        quote: "Цитата",
        callout: "Выноска",
        code: "Код",
        delimiter: "Разделитель",
        image: "Фото",
      },
    },
  },
};

export function getStructuredJournalComposerLabels(
  locale: PublicLocale,
): StructuredJournalComposerLabels {
  return LABELS[locale];
}
