import type { StructuredJournalComposerLabels } from "@/components/garden/structured-journal-composer";
import type { PublicLocale } from "@/lib/public-localization";

const LABELS: Record<PublicLocale, StructuredJournalComposerLabels> = {
  uk: {
    loading: "Завантаження редактора…",
    failureTitle: "Редактор тимчасово недоступний",
    failureBody:
      "Чернетку збережено. Оновіть сторінку, щоб продовжити без втрати тексту й фото.",
    retry: "Спробувати знову",
    silentLoss:
      "Збереження зупинено: частина блоку зникла під час серіалізації.",
    imageChoose: "Додати фото",
    imageUploading: "Обробка фото…",
    imageFailed: "Фото не вдалося підготувати. Запис ще не опубліковано.",
    imageTooLarge: "Фото завелике. Оберіть фото до 50 MiB.",
    imageUnsupported: "Оберіть фото JPEG, PNG, WebP або HEIC.",
    imageRetry: "Повторити фото",
    imageReplace: "Замінити фото",
    imageSetCover: "Використати як обкладинку",
    imageRemove: "Прибрати фото",
    imageRejectRemote:
      "Можна лише файл з пристрою. Посилання й віддалені зображення відхилено.",
    unavailableTitle: "Вміст недоступний",
    unavailableBody: "Цей запис не вдалося безпечно показати.",
    titleLabel: "Заголовок",
    dateLabel: "Дата",
    saveLabel: "Зберегти",
    tools: {
      toolbar: "Панель форматування",
      editor: "Вміст запису",
      paragraph: "Текст",
      header: "Заголовок",
      heading2: "Заголовок другого рівня",
      heading3: "Заголовок третього рівня",
      list: "Список",
      unorderedList: "Маркований список",
      orderedList: "Нумерований список",
      indentList: "Збільшити відступ пункту",
      outdentList: "Зменшити відступ пункту",
      quote: "Цитата",
      quoteAttribution: "Додати автора цитати",
      removeQuoteAttribution: "Прибрати автора цитати",
      delimiter: "Роздільник",
      image: "Фото",
      bold: "Жирний",
      italic: "Курсив",
      link: "Посилання",
      applyLink: "Застосувати",
      cancelLink: "Скасувати",
      undo: "Скасувати зміну",
      redo: "Повторити зміну",
    },
    reorder: {
      moveUp: "Перемістити вгору",
      moveDown: "Перемістити вниз",
      dragHandle: "Перетягнути блок",
      deleteBlock: "Видалити",
      movedAnnouncement: "{type} переміщено на позицію {position} з {total}",
      deletedAnnouncement: "Блок видалено: {type}",
      blockType: {
        paragraph: "Текст",
        header: "Заголовок",
        list: "Список",
        quote: "Цитата",
        delimiter: "Роздільник",
        image: "Фото",
        unknown: "Блок",
      },
    },
  },
  bg: {
    loading: "Зареждане на редактора…",
    failureTitle: "Редакторът временно не е наличен",
    failureBody:
      "Черновата е запазена. Обновете страницата, за да продължите без загуба на текст и снимки.",
    retry: "Опитай отново",
    silentLoss: "Записът е спрян: част от блок изчезна при сериализация.",
    imageChoose: "Добави снимка",
    imageUploading: "Обработка на снимка…",
    imageFailed: "Снимката не можа да бъде подготвена. Записът не е публикуван.",
    imageTooLarge: "Снимката е твърде голяма. Изберете снимка до 50 MiB.",
    imageUnsupported: "Изберете снимка JPEG, PNG, WebP или HEIC.",
    imageRetry: "Опитай снимката отново",
    imageReplace: "Замени снимката",
    imageSetCover: "Използвай за корица",
    imageRemove: "Премахни снимка",
    imageRejectRemote:
      "Само файл от устройството. Връзки и отдалечени изображения са отхвърлени.",
    unavailableTitle: "Съдържанието е недостъпно",
    unavailableBody: "Този запис не може да бъде показан безопасно.",
    titleLabel: "Заглавие",
    dateLabel: "Дата",
    saveLabel: "Запази",
    tools: {
      toolbar: "Лента за форматиране",
      editor: "Съдържание на записа",
      paragraph: "Текст",
      header: "Заглавие",
      heading2: "Заглавие ниво 2",
      heading3: "Заглавие ниво 3",
      list: "Списък",
      unorderedList: "Неподреден списък",
      orderedList: "Подреден списък",
      indentList: "Увеличи отстъпа на елемента",
      outdentList: "Намали отстъпа на елемента",
      quote: "Цитат",
      quoteAttribution: "Добави автор на цитата",
      removeQuoteAttribution: "Премахни автора на цитата",
      delimiter: "Разделител",
      image: "Снимка",
      bold: "Удебелен",
      italic: "Курсив",
      link: "Връзка",
      applyLink: "Приложи",
      cancelLink: "Отказ",
      undo: "Отмени промяната",
      redo: "Повтори промяната",
    },
    reorder: {
      moveUp: "Премести нагоре",
      moveDown: "Премести надолу",
      dragHandle: "Плъзни блок",
      deleteBlock: "Изтрий",
      movedAnnouncement: "{type} е преместен на позиция {position} от {total}",
      deletedAnnouncement: "Блокът е изтрит: {type}",
      blockType: {
        paragraph: "Текст",
        header: "Заглавие",
        list: "Списък",
        quote: "Цитат",
        delimiter: "Разделител",
        image: "Снимка",
        unknown: "Блок",
      },
    },
  },
  ru: {
    loading: "Загрузка редактора…",
    failureTitle: "Редактор временно недоступен",
    failureBody:
      "Черновик сохранён. Обновите страницу, чтобы продолжить без потери текста и фото.",
    retry: "Попробовать снова",
    silentLoss: "Сохранение остановлено: часть блока исчезла при сериализации.",
    imageChoose: "Добавить фото",
    imageUploading: "Обработка фото…",
    imageFailed: "Фото не удалось подготовить. Запись ещё не опубликована.",
    imageTooLarge: "Фото слишком большое. Выберите фото до 50 MiB.",
    imageUnsupported: "Выберите фото JPEG, PNG, WebP или HEIC.",
    imageRetry: "Повторить фото",
    imageReplace: "Заменить фото",
    imageSetCover: "Использовать как обложку",
    imageRemove: "Убрать фото",
    imageRejectRemote:
      "Только файл с устройства. Ссылки и удалённые изображения отклонены.",
    unavailableTitle: "Содержимое недоступно",
    unavailableBody: "Эту запись нельзя безопасно показать.",
    titleLabel: "Заголовок",
    dateLabel: "Дата",
    saveLabel: "Сохранить",
    tools: {
      toolbar: "Панель форматирования",
      editor: "Содержимое записи",
      paragraph: "Текст",
      header: "Заголовок",
      heading2: "Заголовок второго уровня",
      heading3: "Заголовок третьего уровня",
      list: "Список",
      unorderedList: "Маркированный список",
      orderedList: "Нумерованный список",
      indentList: "Увеличить отступ пункта",
      outdentList: "Уменьшить отступ пункта",
      quote: "Цитата",
      quoteAttribution: "Добавить автора цитаты",
      removeQuoteAttribution: "Убрать автора цитаты",
      delimiter: "Разделитель",
      image: "Фото",
      bold: "Жирный",
      italic: "Курсив",
      link: "Ссылка",
      applyLink: "Применить",
      cancelLink: "Отмена",
      undo: "Отменить изменение",
      redo: "Повторить изменение",
    },
    reorder: {
      moveUp: "Переместить вверх",
      moveDown: "Переместить вниз",
      dragHandle: "Перетащить блок",
      deleteBlock: "Удалить",
      movedAnnouncement: "{type} перемещён на позицию {position} из {total}",
      deletedAnnouncement: "Блок удалён: {type}",
      blockType: {
        paragraph: "Текст",
        header: "Заголовок",
        list: "Список",
        quote: "Цитата",
        delimiter: "Разделитель",
        image: "Фото",
        unknown: "Блок",
      },
    },
  },
};

export function getStructuredJournalComposerLabels(
  locale: PublicLocale,
): StructuredJournalComposerLabels {
  return LABELS[locale];
}
